### ISSUE TITLE
HTML field type - Easy and solves many problems

### ISSUE THREAD

**Issue by ghost** [jan-vince/smallcontactform#102]
Hi Jan - I know you've commented on this issue already, but this would be very easy to add and solve many problems.  Just create a new field type called "HTML". Whatever HTML the user puts into a text box, display that exactly. Don't wrap it in anything or put anything else inside it. Just display the user's input. With this field, you could add an opening div class="col1" for example, or later on a closing "/div" or you could put additional text above a series of checkboxes. This has lots of uses!

In my example I wanted to display my form in three columns. Just being able to add my own div's to the form would make it easy. I also needed a way to add more text about a list of checkboxes and there's no way to do this either (that i know of).

**Comment by jan-vince** [comment]
Hi @bmcwilliams,

I have added `Custom code` and `Custom content` field types in version 1.5.

Test it and let me know if there are any problems.


Best regards,

Jan

**Comment by ghost** [comment]
Jan - really good! I see some things that could be adjusted to be more intuitive. The highest thing on the list, probably no need to display those fields when viewing a form submission. 

Notice that col1_open, col2_open, col3_open and col3_close are "code" fields. "send_me_text" and "consent_text" are "content" fields. 

![Screen Shot 2020-08-18 at 1 48 50 PM](https://user-images.githubusercontent.com/40217874/90558812-efd0d100-e159-11ea-9878-fe5840aa280d.png)
