### ISSUE TITLE
Special Fields when viewing form submissions

### ISSUE THREAD

**Issue by ghost** [jan-vince/smallcontactform#103]
Jan - your special fields update are really good! 

I see some things that could be adjusted to be more intuitive. The highest thing on the list - no need to display those special 

![small-contact-form](https://user-images.githubusercontent.com/40217874/90930113-3c651800-e3b7-11ea-8282-964e108c0ce2.png)

fields when viewing a form submission.

Notice that col1_open, col2_open, col3_open and col3_close are "code" fields. "send_me_text" and "consent_text" are "content" fields.

**Comment by jan-vince** [comment]
Hi @bmcwilliams,

I do not have much time right now so feel free to create PR and I will add it to Small Contact Form.

Best regards,

Jan
