### ISSUE TITLE
Validation on Checkbox fields is not showing any message nor error display

### ISSUE THREAD

**Issue by Chocofede** [jan-vince/smallcontactform#104]
Hi Jan, 

What a nice plugin you built! I like it, so easy and fun to use. I'm writing you as I don't know if I misconfigured the validation on checkbox, or if it doesn't work correctly. 

The issue is: When you go to the contact form, if you don't check the checkbox, it doesn't show an error interface as in the textareas nor show any message: 

![Screenshot from 2020-08-25 09-53-56](https://user-images.githubusercontent.com/2053931/91147712-ef37bd80-e6b8-11ea-825d-fc1eb2ecf248.png)

I would expect the message that I wrote in the configuration:
![Screenshot from 2020-08-25 09-52-06](https://user-images.githubusercontent.com/2053931/91147541-b7c91100-e6b8-11ea-8f33-5921bdeb348d.png)

Is that a bug, or did I do something wrong. Hum... after writing this I've realized that it doesn't show ANY validation error message at all (!!) in any field. Is that intended? Does that depends on the configuration?

Thanks!

**Comment by jan-vince** [comment]
Hi @Chocofede,

looks like a bug to me too.

*There was a hardcoded value - probably by mistake.*

This is fixed in 1.47.2 - available on marketplace.


Thank you !

Best regards,

Jan
