### ISSUE TITLE
Successful ajax post shows inputs as invalid

### ISSUE THREAD

**Issue by novastream** [jan-vince/smallcontactform#106]
If I submit a form via AJAX:
- I get a success message
- the data is stored and a notification is sent
- the input fields are cleared

So everything is working except the form has the class "was-validated" and the input fields have a red border (was-validated form-control:invalid).

The issue seems to be solved by removing "was-validated" from SmallContactForm.php (line 552).

Is this an issue with the plugin, bootstrap 4 or is it something I've done wrong?

**Comment by jan-vince** [comment]
Hi @novastream,

I cannot replicate this.

Have you tried this without AJAX?

PS: I believe `was-validated` class is required for B4, [see docs](https://getbootstrap.com/docs/4.5/components/forms/#how-it-works).
