### ISSUE TITLE
Checkbox validation throwing an error: 

### ISSUE THREAD

**Issue by sdlb** [jan-vince/smallcontactform#107]
Hi Jan,
First of all, thank you for this plugins wich is a great time saver.
I'm working on version 1.48.2.
My form has a checkbox for GDPR acceptance, but validation under "required" throws an error: 
An exception has been thrown during the rendering of a template ("Undefined index: class").
D:\DEV\bca/plugins/janvince/smallcontactform/components/smallcontactform/scf-form.htm line 11
Validation under "accepted" throws the same error.
It seems to be similar to the issue Chocofede encountered.
Can you help?

**Comment by sdlb** [comment]
Validation under "accepted" trhows the same error.

**Comment by jan-vince** [comment]
Hi @sdlb and thanks - this is fixed in 1.48.3.

Best regards,

Jan
