### ISSUE TITLE
Event needed to extend SCF

### ISSUE THREAD

**Issue by sdlb** [jan-vince/smallcontactform#109]
Hi Jan,
Thank you for 1.48.3 update. You've been really fast.
Not an issue but I plan to extend SCF with a smal plugin.
The idea is to use the dropdown field to select a specicific recipient for the notification email through the boot method.
But I didn't find an event to hook on (unless I missed it).
I guess that it could be great addition for other further extensions too.

**Comment by jan-vince** [comment]
Hi @sdlb, I have no events present in Small Contact Form plugin, but I agree this is a place to improve :)

If you have time, you can create PR and will add it. Right now I have not much spare time.

Best regards,

Jan
