### ISSUE TITLE
Error on settings.php

### ISSUE THREAD

**Issue by aswlauris** [jan-vince/smallcontactform#11]
Invalid argument supplied for foreach()
...../plugins/janvince/smallcontactform/models/Settings.php line 321

i read that it was fixed, but i still get it on v. 1.4.3

**Comment by jan-vince** [comment]
It wasn't handled correctly so I have added default empty array to be returned from ````getEnabledNonEnglishLocales()```` method.

Can you please check version 1.4.4 and let me know?

**Comment by aswlauris** [comment]
Fixed.
