### ISSUE TITLE
Expected response code 250 but got code "550"

### ISSUE THREAD

**Issue by ProtoQuestInc** [jan-vince/smallcontactform#110]
I'm using Cloudways as a host, do I need additional setup steps to get this plugin working? Below is what I get when I submit the form. The submissions get stored in the CMS backend, but no notification emails get sent out.

![Screen Shot 2020-10-12 at 2 07 07 PM](https://user-images.githubusercontent.com/71284890/95786147-4529ea00-0c94-11eb-8f17-7fee965cb74c.png)

**Comment by jan-vince** [comment]
Hi @mismail0, this is mostly a problem in email address.

You have a mailbox you are logging in with but in Contact Form configuration you have entered different one.

And mail server will not allow you to send email in behalf of other email address than your mailbox has.

First of all open any of email templates in OctoberCMS backend (Settings > Mail templates) and click button `Send test message` at bottom.

If this not work, you have a problem in general mail configuration (Settings > Mail configuration).

If this do work, check Small Contact Form configuration (tab Email).

If you need sent email from Contact Form to be replied to specifi address, there is a field for it.


Let me know.

Jan

**Comment by ProtoQuestInc** [comment]
@jan-vince, thank you so much! That's exactly what I needed. It's working now. Awesome plugin!
