### ISSUE TITLE
Form is not submitting

### ISSUE THREAD

**Issue by tailsdev** [jan-vince/smallcontactform#111]
First of all, thanks for this plugin!

I'm interested on using it and it is my first time using. I configured my e-mail in october panel (gmail, smtp), configured the contact form and added the component to my page.. then when I started to test:

the form acts as it sended the data, but I don't receive any message in the message board, and also I didn't received any e-mail in my inbox

can't find anything in the documentation that can help me, so I came here. Do you guys know what may be happening?

thanks in advance! =)

**Comment by jan-vince** [comment]
Hi @tailsdev anything in system log?

**Comment by tailsdev** [comment]
I just figured out what was going on and I hope I can help someone else:

**plugin MUST be on page level! it cannot be used on partials (in October CMS)**

I was using in partials and wasn't working.. then when I moved plugin to page level it worked like a charm!

anyway: thank you to answered me so quickly!

and thank you for this awesome plugin!

**Comment by jan-vince** [comment]
Ok :)

And just to be clear - component definition has to be on layout or page, but component call {% component %} can be placed in partial. If you need it to use this way (as I do :)

Best regards,

Jan
