### ISSUE TITLE
Receiving messages in the inbox (database) but not in e-mail (gmail)

### ISSUE THREAD

**Issue by tailsdev** [jan-vince/smallcontactform#112]
Hello,

I configured the contact form and its working halfway

Now my website receive messages in the inbox (database) but not in e-mail (gmail)

I'm leaving someting behind?

Thanks in advance! =)

**Comment by jan-vince** [comment]
Hi @tailsdev,

first of all test that mail system is working - open in Setting > Mail templates, open any of templates and hit button `Send test message` at the bottom.

If you receive email, go to Settings > Contact form, open tab `Email` and check that you have entered valid email addresses.

Also look in Setting > Event log for any errors from Contact form.


Best regards,

Jan

**Comment by tailsdev** [comment]
Hello,

Just tested your steps:

I sent the test message and received the e-mail

And there is nothing in the Event Log :(

do you have another suggestion for me to try?

thanks in advance!

**Comment by jan-vince** [comment]
Just to be sure:

* You have allowed to send email notifications and/or autoreply in Settings > Contact form > tab Email

* You can successfully send contact form


If so, try to change Mail method to `Log file` in Settings > Mail configuration and send a form.

In Settings > Event log you should see logged email/s. 

If so, the problem will be in mail delivery itself - means Contact form sends email, October mail system delivers it but Gmail (or other provider) do not deliver it.

If you don't see any logged emails, problem is in Contact form settings or usage (Contact form component has to be in layout or page, not in partial).

**Comment by tailsdev** [comment]
Thanks again for your answer!

Yep, you were right. I enabled autoreply and notifications and appeared an error in the Event Log.

Do you have any tip where I should look at now? Thanks in advance!

Below, the error with full stack trace:

Swift_TransportException: Expected response code 354 but got code "421", with message "421 4.7.0 UBMSA01.spo2.umbler.com Error: too many errors
" in /home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457
#0
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341):
Swift_Transport_AbstractSmtpTransport->assertResponseCode('421 4.7.0 UBMSA...', Array)
#1
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305):
Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\r\n', Array, Array, false, NULL)
#2
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390):
Swift_Transport_EsmtpTransport->executeCommand('DATA\r\n', Array, Array)
#3
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(497):
Swift_Transport_AbstractSmtpTransport->doDataCommand(Array)
#4
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516):
Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'rodrigobsorrego...', Array, Array)
#5
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206):
Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'rodrigobsorrego...', Array, Array)
#6
/home/raf.adv.br/public/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71):
Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451):
Swift_Mailer->send(Object(Swift_Message), Array)
#8
/home/raf.adv.br/public/vendor/october/rain/src/Mail/Mailer.php(115):
Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221):
October\Rain\Mail\Mailer->send('janvince.smallc...', Array, Object(Closure))
#10
/home/raf.adv.br/public/plugins/janvince/smallcontactform/models/Message.php(460):
Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#11
/home/raf.adv.br/public/plugins/janvince/smallcontactform/components/SmallContactForm.php(411):
JanVince\SmallContactForm\Models\Message->sendNotificationEmail(Array, Array, 'contactForm', NULL)
#12
/home/raf.adv.br/public/modules/cms/classes/ComponentBase.php(187):
JanVince\SmallContactForm\Components\SmallContactForm->onFormSend()
#13
/home/raf.adv.br/public/modules/cms/classes/Controller.php(851):
Cms\Classes\ComponentBase->runAjaxHandler('onFormSend')
#14
/home/raf.adv.br/public/modules/cms/classes/Controller.php(742):
Cms\Classes\Controller->runAjaxHandler('contactForm::on...')
#15
/home/raf.adv.br/public/modules/cms/classes/Controller.php(374):
Cms\Classes\Controller->execAjaxHandlers()
#16
/home/raf.adv.br/public/modules/cms/classes/Controller.php(225):
Cms\Classes\Controller->runPage(Object(Cms\Classes\Page))
#17
/home/raf.adv.br/public/modules/cms/classes/CmsController.php(50):
Cms\Classes\Controller->run('contato')
#18
[internal function]:
Cms\Classes\CmsController->run('contato')
#19
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54):
call_user_func_array(Array, Array)
#20
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45):
Illuminate\Routing\Controller->callAction('run', Array)
#21
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212):
Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Cms\Classes\CmsController), 'run')
#22
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169):
Illuminate\Routing\Route->runController()
#23
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658):
Illuminate\Routing\Route->run()
#24
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30):
Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25
/home/raf.adv.br/public/plugins/rainlab/translate/classes/LocaleMiddleware.php(29):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
RainLab\Translate\Classes\LocaleMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#27
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#30
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#36
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#39
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(68):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#42
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635):
Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601):
Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#47
/home/raf.adv.br/public/vendor/october/rain/src/Router/CoreRouter.php(20):
Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#48
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176):
October\Rain\Router\CoreRouter->dispatch(Object(Illuminate\Http\Request))
#49
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30):
Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#50
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51
/home/raf.adv.br/public/vendor/october/rain/src/Foundation/Http/Middleware/CheckForMaintenanceMode.php(25):
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149):
October\Rain\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#53
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53):
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56
/home/raf.adv.br/public/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116):
Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57
/home/raf.adv.br/public/index.php(43):
Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58
{main}

**Comment by jan-vince** [comment]
You will have to test with different SMTP server or consult with your provider. 

Error `421 4.7.0 UBMSA01.spo2.umbler.com Error: too many errors ` is not much verbose.
