### ISSUE TITLE
Basic form with name, email, message results in error with email field

### ISSUE THREAD

**Issue by rhdalton** [jan-vince/smallcontactform#113]
Hi,

I installed the plugin and set up a form with 3 basic input fields, name, email address and message. Whenever I try to submit the form, it returns the generic error 'There was an error sending your data!' with the email field highlighted as the invalid field. However, I am submitting a valid email address.

Is there some setting I'm not seeing?

**Comment by jan-vince** [comment]
Hi @rhdalton 

what is in your Event log? (Settings > Event log).

What is your settings of Contact Form, can you post screenshots?

Try to check:

* Email settings (are you able to send a test message from Email templates?)
* Event log for detailed error info
* Developer tools (error console) for any problems with JavaScript (if you use Ajax for sending)

**Comment by rhdalton** [comment]
I did some more testing, and discovered its problem with Email validation options. When I add "Required" validation, the form fails to submit, even when the email is valid. Also I noticed, when I add "Email" validation (with required validation off), the form will submit, even if the value is not an email address. These validation issues only appear on the email input field.

Also noticed when the form is successfully submitted the message log does not log the email address field, even though I've mapped the email column to the email field.

Nothing in event logs, no errors in console, and I have email settings all off.

![Capture](https://user-images.githubusercontent.com/933606/99830959-48c25380-2b13-11eb-8046-ba3fb8f43caf.PNG)
![Capture2](https://user-images.githubusercontent.com/933606/99830982-4eb83480-2b13-11eb-8c23-cee96a6e4734.PNG)

**Comment by jan-vince** [comment]
Try to change email field name to something short like 'email' as this is used for name attribute and validation. 
There is a label field for long descriptions.

**Comment by rhdalton** [comment]
That fixed the problem, I didnt notice the small text under the email field.  Thanks for the help.

**Comment by jan-vince** [comment]
No problem :)
