### ISSUE TITLE
Beginner issue with resizing an input form

### ISSUE THREAD

**Issue by seanjkanderson** [jan-vince/smallcontactform#114]
Hi Jan,

Not really an issue with the contact form plug-in per se, but I am having trouble setting the css to make an input box bigger. I'm trying to make the box bigger to take in multi-messages that one might leave on a website in lieu of sending an email.

For example, a [pretty standard form](https://www.alexnoriega.com/contact) on a photography website.

When I tried setting the height, it just vertically centers the text. Any tips?

I do have the default css that I'm trying to modify:
```
.form-control {
    margin-bottom: 30px;
    font-size: 14px;
    font-style: italic;
    height: 60px;
    border-bottom: 2px solid #c0c0c0;
    border-top: 0;
    border-left: 0;
    border-radius: 0;
    border-right: none;
    background-color: transparent;
    -webkit-transition-duration: 500ms;
    transition-duration: 500ms;
}
```

Thanks,
Sean

**Comment by jan-vince** [comment]
Hi @seanjkanderson, I probably do not fully understand what you are trying to do :(

If you need to enter more text (in more lines) you need to use `textarea` field type.

If you need something else please try to post some visual explanation.


Jan

**Comment by seanjkanderson** [comment]
Ah I just figured this out and was about to close it. Thanks for your help, textarea was exactly what I needed.
