### ISSUE TITLE
Confirmation email is not showing the sender's name

### ISSUE THREAD

**Issue by Dione-stack** [jan-vince/smallcontactform#115]
Using {{ name }} in Contact form confirmation template is not showing the sender's name from the contact form, how can i make that possible? thank you

**Comment by jan-vince** [comment]
Hi @Dione-stack,

you have to iterate through arrays: https://github.com/jan-vince/smallcontactform#email

There should be example in default email templates.

**Comment by Dione-stack** [comment]
I thought i could use it out of the box, i'm sorry for taking a little of your time and thank you for your quick response and for this amazing plug in, have a wonderful day
