### ISSUE TITLE
Queue works but doesn't send email

### ISSUE THREAD

**Issue by acetas** [jan-vince/smallcontactform#116]
Hi there,
Queue works, data comes to jobs table in database, but mail is not sent.
Test mails are also successful

**Comment by acetas** [comment]
@jan-vince can u help me?
![Screenshot_6](https://user-images.githubusercontent.com/22733102/106836038-75652080-66a9-11eb-91d0-e2de05bc6b24.png)

**Comment by jan-vince** [comment]
HI @acetas, do you have [working cron](https://octobercms.com/docs/setup/installation#crontab-setup)?

**Comment by acetas** [comment]
where am i doing wrong @jan-vince ?
![cron](https://user-images.githubusercontent.com/22733102/106892336-fd284a80-66fc-11eb-8abd-0377a6071071.png)

![Screenshot_8](https://user-images.githubusercontent.com/22733102/106893385-8c822d80-66fe-11eb-9391-fce81ab9fcbb.png)

**Comment by jan-vince** [comment]
Have you tried to fire this from console with `php artisan schedule:run` ?

**Comment by acetas** [comment]
Can you explain it more understandable than the beginner level @jan-vince ?

**Comment by jan-vince** [comment]
How about not to use the queue? You can send messages from Contact Form directly (I don't use queue on any of my projects).

But if you want to test it - just open terminal, go to your project's folder and run this command:

`php artisan schedule:run`

It will trigger queue immediatelly and you can test that mails have been sent.

**Comment by acetas** [comment]
Thank you for your answer @jan-vince . 
Yes My plan B is not to use this queue. However, I liked the instant response of that. I know how to run this console code you mentioned while working in local yes, but I don't know how to run it when in shared hosting (it should probably be over cPanel).

**Comment by jan-vince** [comment]
@acetas Does it work localy?

If so, you will have to look in your hosting config.

In my case (Czech Republic) shared hosting does not allow to run console PHP scripts and I have to turn them from PHP scripts.

Or you can try Vojta Svoboda's plugin: https://octobercms.com/plugin/vojtasvoboda-webartisan

**Comment by acetas** [comment]
yes, i will try that too. If not, continue with plan b :) 
Thank you very much for your answers.

**Comment by jan-vince** [comment]
Hi @acetas,

this is my setup for queue on shared hostings:


1) Create CMS page:

```
title = "artisan"
url = "/artisan/schedule"
is_hidden = 0
==
<?php

function onStart(){

    \Artisan::call('schedule:run');

}
?>
==
```


2) On your hosting add a cron job with URL like: `https://www.mydomain.com/artisan/shedule`.



---

If your shared hosting doesn't support this (but it should), you can probably bypass this by calling artisan by page load (Wordpress is doing something simillar).

So you can add 

```
<?php

function onStart(){

    \Artisan::call('schedule:run');

}
?>
```

to your layout, page or partial.


Or you can use some free ping service like https://www.site24x7.com/ping-test.html.

Let me know if this works for you.

**Comment by acetas** [comment]
Hello again @jan-vince ,

I did exactly what you said. However, an arrangement had to be made. It works when I edit it as follows and open the page.

At this step, I have a few questions:

1- Do I need to create a cron on cPanel and make it open this page regularly?

2- When I open https://www.mydomain.com/artisan/shedule, the page does not respond, it always says mydomain.com is expected. Sometimes it gives a 503 error. It still works, but do you think this is a problem? Is it something that will tire the processor etc, slow down the site?

- Thank you for your attention.

```
<?php

function onStart(){

    \Artisan::call('queue:work');

}
?>
```

**Comment by jan-vince** [comment]
ad 1) Unless you (or some service) open that page, queue will not be processed and no mails will be sent.

ad 2) Try to look inside your backend in System log if any errors there.

If you see no errors you will probably have to create a local dev environment (with MAMP or WAMP) and start testing with console `php artisan queue:work`.

*Just to be sure - you have substituted www.mydomain.com with your domain (like https://www.vince.cz/ )?*

**Comment by acetas** [comment]
Yes I checked mydomain by replacing it with my own domain name.

Well then I'll try these steps you mentioned
