### ISSUE TITLE
How can i show page title?

### ISSUE THREAD

**Issue by acetas** [jan-vince/smallcontactform#117]
Hello,

How can I show the name of the page where the form is sent in the subject and content of the notification email?

**Comment by jan-vince** [comment]
Hi @acetas, you can use `form_description` field.

In component definition, you can save your page name like this: `{% component 'myForm' form_description = (this.page.title) %}`

In email you can access this with `{{fields.form_description}}`.

**Comment by acetas** [comment]
it's work. Thank u.
