### ISSUE TITLE
Placeholder

### ISSUE THREAD

**Issue by Engelb64** [jan-vince/smallcontactform#118]
excuse my bad english, i'm looking for a way to add placeholder to the fields created through the plugin

**Comment by jan-vince** [comment]
Hi @Engelb64, there is a checkbox in plugin's settings:

![Snímek obrazovky 2021-02-04 v 8 50 16](https://user-images.githubusercontent.com/1104383/106861437-0c3fd600-66c6-11eb-985a-91cf2c8365f6.png)

**Comment by Engelb64** [comment]
I'm looking for something more like a placeholder and a separate label

![image](https://user-images.githubusercontent.com/43185036/106902233-95570d00-66c6-11eb-9547-fa728934afd5.png)

**Comment by jan-vince** [comment]
You can do this just with CSS.

Check option `Use placeholders` and in CSS add:

`
.form-group label {
display: block!important;
}
`

Labels are present in HTML and just hidden by `style` attribute.
