### ISSUE TITLE
403 Permission Error

### ISSUE THREAD

**Issue by acetas** [jan-vince/smallcontactform#119]
Hi @jan-vince ,

I get this error after uploading the project in shared hosting. What should I do?

![Screenshot_7](https://user-images.githubusercontent.com/22733102/106836320-00deb180-66aa-11eb-8c26-8927d831a3de.png)

**Comment by jan-vince** [comment]
Hi @acetas, this is probably due wrong permissions on your files and/or folders.

Many shared hostings have an option to repair permissions.

**Comment by acetas** [comment]
I talked to the hosting company. They edited the modsec rules and now it works.
