### ISSUE TITLE
Notification email template

### ISSUE THREAD

**Issue by gergo85** [jan-vince/smallcontactform#12]
I have two problem:

1. I added an own notification email template, but the plugin use the default one.
2. The janvince.smallcontactform::mail.autoreply template doesn't show on the list of Mail template page.

**Comment by jan-vince** [comment]
Hi, both should be fixed in version 1.4.5.

1. There was database template check missing.
2. Templates were registered only if locale matched. Now the default (English) templates will be registered always.

Can you please check new version in your setup and let me know?

**Comment by gergo85** [comment]
Thank you for fast update!

The both problem is solved, but I found the another one :( The variables of template dont't work. For instance I used the {{email}}, but it doesn't appear on the sending email.

**Comment by jan-vince** [comment]
There is only {{ fields }} array available inside of email templates.

If you have custom field with name 'email', it will be available as ````{{ fields.email }}````.

Is this what you are looking for?

*I will make documentation more clear about this in next release.*

**Comment by gergo85** [comment]
I see, it works.

In the sending mail how to add newlines to the message field?

**Comment by jan-vince** [comment]
Try {{ fields.message|nl2br }}

**Comment by gergo85** [comment]
Thank you very much!

**Comment by jan-vince** [comment]
You are wellcome :)

Thank you for the issue and your time while testing!
