### ISSUE TITLE
Hidden form field with default value from twig?

### ISSUE THREAD

**Issue by nico-fonte** [jan-vince/smallcontactform#121]
Hi there,
I can't get my head around if there is a way to have a hidden field in the form, with default value taken from twig coming from another Octobercms plugin's component placed in the same page.

**Comment by jan-vince** [comment]
Hi @nico-fonte,

this is not supported out of the box but you can use custom code field and insert whatever you need.

For sending data from template to form you can also use [description field](https://github.com/jan-vince/smallcontactform#overriding-form-settings).

**Comment by nico-fonte** [comment]
Hi @jan-vince,
thank you for your reply.

Hidden field works flawlessly, anyway I can't make the twig value work.
This is my code for the custom code field of the form

`<input type="hidden" id="event" name="event" value="{{ event.name }}">`

The form is used in this section of the my page:

            {% for event in events %}
                {% if event.time_begin > date() %}
                      <div class="box">
                        <div class="row">
                          <div class="col-md-3 text-center">
                            <h6>{{ event.location_city }}</h6>
                            <p>{{ event.location_street }} {{ event.location_number }}</p>
                            <h6>{{ event.time_begin | date('d') }}/{{ event.time_begin | date('m') }}/{{ event.time_begin | date('y') }} <br> {{ event.time_begin | date('H:i') }}</h6>
                          </div>
                          <div class="col-md-6 text-center description">
                            <h6>{{ event.name }}</h6>
                            {{ event.description }}
                          </div>
                          <div class="col-md-3 text-center"><div class="section-button"><a href="/incontri/{{ event.slug }}"><div class="button">subscribe</div></a></div></div>
                        </div>
                      </div>
                      <hr>
                     <h4>Please type in your details</h4>
                    
                     {% component 'contactForm' %}
                {% endif %}
            {% endfor %}

When I hit subscribe, I receive an email where the field Event is empty, when I tried with test value not from twig, works perfectly.

**Comment by jan-vince** [comment]
Hi @nico-fonte,

try to use `form_description` field:

`{% component 'myForm' form_description = event.name %}`

In email template you can access this with `{{fields.form_description}}`.

**Comment by nico-fonte** [comment]
Amazing, it works perfectly.

Thank you so much!
