### ISSUE TITLE
"Trying to get property 'uploads' of non-object" error

### ISSUE THREAD

**Issue by dieffe69** [jan-vince/smallcontactform#122]
Hi there, I have updated the plugin to its latest release (currently 1.51.1).

Now when I disable messages saving it returns a **Trying to get property 'uploads' of non-object** error message (line 261 in _/web/htdocs/www.modumformazioneinestetica.it/home/anteprima/plugins/janvince/smallcontactform/models/Message.php line 261_).

My contact form contains no upload inputs... unchecking the Disable message saving box will return the form to work.

Has anybody stumbled upon the same issue?

**Comment by jan-vince** [comment]
Hi @dieffe69 and thank you - I have fixed this in version 1.51.2.

Best regards :) 

Jan
