### ISSUE TITLE
Takes a long time to respond

### ISSUE THREAD

**Issue by acetas** [jan-vince/smallcontactform#123]
Hello there,

It takes a long time to get a response after the form is submitted. How can we speed this up or the speed of sending mail? Could there be an improvement that we can make in this sense? Also, can we determine exactly why it's taking so long?

**Comment by jan-vince** [comment]
Hi @acetas 

I guess it waits for SMTP reply (if you have enabled notification and/or autoreply emails to be sent).

Try to disable email sending (in Settings > Small Contact Form > Email) or you can change October's email settings to send in Log.

**Comment by acetas** [comment]
yes @jan-vince , it is delayed because it waits for an answer from the mailing. Can't we turn this off? So can you write success without waiting for the reply of the mail sending?

**Comment by jan-vince** [comment]
@acetas 

sure - use queue.

There is an option in Small Contact Form to turn this on and in docs there is a link to October documentation, how to prepare it

**Comment by acetas** [comment]
@jan-vince 
Unfortunately I couldn't run queue on shared hosting.  ( https://github.com/jan-vince/smallcontactform/issues/116 )

So I'm looking for an answer to such a question: /

Can we make it possible to respond without using queue and waiting for the mail response ? (It will send the mail anyway)

**Comment by jan-vince** [comment]
Hi @acetas, I have many sites on shared hostings and I am able to run queue - so let's try to fix that first.

I will reopen #116 and add my setup.
