### ISSUE TITLE
ReCAPTCHA fails due to allow_url_fopen=0

### ISSUE THREAD

**Issue by GamertechAU** [jan-vince/smallcontactform#124]
After updating the contact form, form messages are failing to be sent with Google CAPTCHA enabled, generating the error below.

`file_get_contents(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0`

allow_url_fopen should remain disabled for security. Any workaround for this?

**Comment by jan-vince** [comment]
Hi @Gamertech,

this is not caused by an update. 

Your server is configured to disable PHP `file_get_contents()` function.

Without this function reCaptcha cannot be checked.

Only solution is to enable this function or disable reCaptcha.

**Comment by GamertechAU** [comment]
I've disabled it and moved to the passive anti-spam you've added for the time being, but enabling allow_url_fopen hasn't been a good idea in years.

Google added an alternative method using POST back in 2015. Maybe a setting in the backend to swap between default and the safe method?

https://github.com/google/recaptcha/issues/36#issuecomment-90549894

**Comment by jan-vince** [comment]
Hi @Gamertech,

on my shared hostings `allow_url_fopen` can be enabled/disabled with no problem so I have never needed this (and I don't know about any security risk keeping this enabled).

I will check this as soon as I have some spare time.

Best regards,

Jan

**Comment by GamertechAU** [comment]
When enabled, it allows users to inject commands using remote urls.

As soon as I disabled ReCaptcha, and enabled the passive anti-spam, the form started getting hammered by spam bots. DMARC is taking care of them, but I'd much prefer to get ReCaptcha back up and running.

Know where I can modify your files to make the change linked above and swap it to post? Been looking through the plugin files, but can't find a similar section.

Thanks

**Comment by jan-vince** [comment]
Hi @Gamertech 

I have added google/recaptcha library in 1.52.1. so you can test it.

Best regards,

Jan

**Comment by GamertechAU** [comment]
Works perfectly. Thanks for the fast work Jan
