### ISSUE TITLE
Validation error messages for each language in Translate Messages Dictionary

### ISSUE THREAD

**Issue by massimomegistus** [jan-vince/smallcontactform#125]
Hello,
I've just noticed that form fields labels appear in dictionary in the default language, as expected, while validation error messages are added for each language, after the first post submit in that language
For example, "the company field is required" and "The email field is required" are two validation error for the default language in Translate messages datatable
<img width="859" alt="Schermata 2021-06-05 alle 12 21 41" src="https://user-images.githubusercontent.com/39944924/120888587-547def00-c5f9-11eb-96bf-4f43b1a95069.png">
And the corresponding records "company wird benötigt" and "email wird benötigt" are not useful, because traslations can be added to Default language records
<img width="858" alt="Schermata 2021-06-05 alle 12 22 13" src="https://user-images.githubusercontent.com/39944924/120888621-99a22100-c5f9-11eb-882e-4688ea09b0cf.png">
<img width="853" alt="Schermata 2021-06-05 alle 12 22 25" src="https://user-images.githubusercontent.com/39944924/120888626-9e66d500-c5f9-11eb-8043-c1aa3a5e960e.png">

What do you think about it?

**Comment by massimomegistus** [comment]
Hello, I'm here again.
I've realized that adding a validation error for each field solves the issue, each message is translatable as expected.
Anyway, adding Translate Message records on form submit for default language only could be an idea.
Thank you for your work!

**Comment by massimomegistus** [comment]
Hello Jan,
I'm here again. I was wrong, even adding a validation error in the field definition, when the message is translated in a certain language, its translation in added in the Translate messages datatable as a new record
for example, "the company field is required" (in EN default language) once translated in Italian generates a new Translate Message Record "Il campo company è obbligatorio"
<img width="980" alt="Schermata 2021-06-09 alle 11 53 42" src="https://user-images.githubusercontent.com/39944924/121334064-a2586700-c919-11eb-8021-a49eb57b97c2.png">
This is the unwantend entry
<img width="980" alt="Schermata 2021-06-09 alle 11 46 25" src="https://user-images.githubusercontent.com/39944924/121334213-c320bc80-c919-11eb-88b8-43878e467c85.png">
This should be avoided by creating Translate messages entries only when submitting the form in the site default language.

By the way, fields label behaviour is ok, they are not replicated even after translating them

Let me know what do you thing.
Thank you

**Comment by massimomegistus** [comment]
Hello Jan,
I have a possible fix proposal
In JanVince\SmallContactForm\Components\SmallContactForm row 658 change this row
$output[] = '<small class=" invalid-feedback">' . Settings::getDictionaryTranslated($this->postData[$fieldSettings['name']]['error']) . "</small>";
to this
$output[] = '<small class=" invalid-feedback">' . $this->postData[$fieldSettings['name']]['error'] . "</small>";

postData[$fieldSettings['name']]['error'] contains the right translation yet, so Settings::getDictionaryTranslated call should be removed

**Comment by jan-vince** [comment]
Hi @massimomegistus,

I believe this was some of the first try to translate validation messages.

I personally do not use this as I always create fields list for each locale (you can switch fields list to other locale by click on locale shortcut in right upper conner).

![scf-locale](https://user-images.githubusercontent.com/1104383/121338217-953d7700-c91d-11eb-99b4-e55227ca9efd.png)

**Comment by massimomegistus** [comment]
Hi @jan-vince,
this specific site has 8 different locales, so I would prefer to avoid field repeater redefinition, but
changing
$output[] = '' . Settings::getDictionaryTranslated($this->postData[$fieldSettings['name']]['error']) . "";
to
$output[] = '' . $this->postData[$fieldSettings['name']]['error'] . "";

solves the issue, because postData[$fieldSettings['name']]['error'] contains the translated error 

$validationMessages[($field['name'] . '.' . $rule['validation_type'] )] = Settings::getDictionaryTranslated($rule['validation_error']);

and the additional getDictionaryTranslated call is not necesary. 
Do you agree?

**Comment by jan-vince** [comment]
I will keep this open and test it when I have a time. Thanks for issue!

**Comment by massimomegistus** [comment]
You are welcome!

**Comment by jan-vince** [comment]
Hi @massimomegistus and sorry for the delay.

I have tested it and fixed in 1.62.0 version.

Thank you!

**Comment by massimomegistus** [comment]
Hi @jan-vince , great!
