### ISSUE TITLE
Cannot add new form fileds

### ISSUE THREAD

**Issue by heybran** [jan-vince/smallcontactform#127]
Hi Jan,

Greeting from Brandon in China. Firstly I install October CMS locally with MAMP on mac, and then install small contact form plugin with composer, didn't do any settings inside small contact area. And then later this afternoon, I upload project folder to share hosting and login into my backend, I was not able to add form fields. What might be the issue here? Sorry to bother you give that I'm only a rookie developer who don't have the knowledge to fix the issue myself. 
Any suggestions would be much appreciated.

**Comment by jan-vince** [comment]
Hi Brandon,

do you see any errors in backend? (in Settings > System log)

Localy in MAMP it worked?



Best regards,

Jan

**Comment by heybran** [comment]
Hi Jan,

No errors, I click add new fields, circle spins and then no response, no error message either. 

And there is no log. But it works locally.

So I guess the issue comes with my shared hosting?

Thanks,
Brandon

**Comment by jan-vince** [comment]
Looks like this is an issue with your hosting.

If you have access to hosting's apache/php logs, you will probably be able to find more info there.


I haven't saw this problem yet so I can't tell what could be wrong :(






Jan

**Comment by heybran** [comment]
Thanks. I will try to contact hosting company and ask them to check out the logs.

**Comment by heybran** [comment]
Hi Jan,

I upload the project folder to another directory of my shared hosting, and it works, I can add new fields.

So I guess my hosting was just fine though...

Many thanks for the great plugin.

Best regards,
Brandon
