### ISSUE TITLE
Checkbox Validation Message showing wrong language

### ISSUE THREAD

**Issue by nico-fonte** [jan-vince/smallcontactform#128]
Hi jan-vince,
I have a checkbox in the form I created, when not ticked it shows the message "Please tick this box if you want to proceed." which is supposed to be there, but what I need is the message in Italian as the rest of my site is set, plugins, backend, frontend etc..
I probably missed something but I can't figure it out by myself. Any advice on this?

Many thanks

**Comment by jan-vince** [comment]
Hi @nico-fonte,

if you use Rainlab Translate, you can change language for fields in right upper conner of fields repeater in Fields tab. 


Or you can translate form fields in Sertings > Translate messages.

**Comment by nico-fonte** [comment]
Thank you for your reply, that was something I have done prior to my request, both of them, with no luck though.
I'll keep digging to find the issue.

Thank you

**Comment by jan-vince** [comment]
Can you post screenshot of fields definition? What version of October and Small Contact Form you have?

**Comment by nico-fonte** [comment]
SmallContactForm v 1.50.1
OctoberCms build 471

![screencapture-alikristallo-it-backend-system-settings-update-janvince-smallcontactform-settings-2021-08-10-09_38_21](https://user-images.githubusercontent.com/9097088/128828083-fe2d1b58-4033-4f77-aa7f-782d7ac32073.png)

**Comment by jan-vince** [comment]
Hi @nico-fonte,

I have tested this but I can't replicate your problem :(

I have clean October installation (473) and latest Small Contact Form (1.52.1) and in fields I have two languages.

When I switch languages on frontpage I get messages in correct locale.

But you can try:

* disable Rainlab Translate plugin for a moment and test with italian set as default language in October config
* try to disable AJAX in Contact Form settings and test form sending
* try on clean October installation first without Translate plugin and than with it


Let me know.

**Comment by nico-fonte** [comment]
Hi Jan,
sorry for getting back to you just now. I had a stop on that project, due to the client. 

Anyway I was working on validating a form in React JS today and I discovered that the message of “Please check this box if you want to proceed” has something to do as a standard message delivered by the browser, depending on the language I am using on my system, I think that's why I wasn't getting any other language but the English one.
