### ISSUE TITLE
Special HTML characters

### ISSUE THREAD

**Issue by gergo85** [jan-vince/smallcontactform#13]
My language (Hungarian) have some special characters, for example: á é ö ü

The html_entity_decode function convert them. So the sending email doesn't look good.

**Comment by jan-vince** [comment]
I use my plugin with Czech language where we have also many accented characters and I haven't seen any problem so far.

Where is the problem - Html or Plain text email? 

*What email client do you use to read sent messages.*

**Comment by gergo85** [comment]
- I use the HTML mode.
- In the plugin the message is right.
- In the Thunderbird has a problem.

**Comment by gergo85** [comment]
And I sent the test message via October and there is no problem in the Thunderbird.
