### ISSUE TITLE
Order of <input> and <label>

### ISSUE THREAD

**Issue by ARL-Steve** [jan-vince/smallcontactform#131]
The plugin writes html in the order of label html tag then the input html tag. However, the frontend library I'm using for the site I develop assumes that these are in the opposite order - input then label. 

The current output:
`    <label class="control-label form-label required" for="example" style="margin-left: 0px;">Test</label>`
`    <input id="example" class="form-control" name="example" autofocus="" type="text" required="">`

Required output:
`    <input id="example" class="form-control" name="example" autofocus="" type="text" required="">`
`    <label class="control-label form-label required" for="example" style="margin-left: 0px;">Company Name</label>`

How easy is it to swap the order?

**Comment by jan-vince** [comment]
Hi @ARL-Steve, 

probably two options (as this is hard coded in component):

a) Fork my plugin and do changes as you like in PHP code.

b) Override component's view and add form code by hand. This can be quite tricky but doable.


Best regards,

Jan

**Comment by ARL-Steve** [comment]
Hi @jan-vince 

I've gone with option a) and moved the label code to after the generation of the inputs.

Thank you for the suggestion.
