### ISSUE TITLE
Error when submitting form

### ISSUE THREAD

**Issue by nitro9net** [jan-vince/smallcontactform#132]
Getting the following error when I try to submit:

"AJAX handler
'contactForm: onMailSend' was
not found." on line 753 of /home/
**********/public_html/
modules/cms/classes/
Controller.php

I’m using the latest version of WinterCMS.

**Comment by jan-vince** [comment]
Hi,

I would say you have component inside partial - but it has to be in layout or page.



Best regards,

Jan


< Ing. Jan Vince / webdesigner / +420 733 127 581 / www.vince.cz />

**Comment by nitro9net** [comment]
Got it to work. Upgraded to latest wintercms (was 2 behind) and removed and reinstalled the plug-in. Installed with composer this time.

Thank you!
