### ISSUE TITLE
Recaptcha validation fails everytime on form submit

### ISSUE THREAD

**Issue by kavishdahekar** [jan-vince/smallcontactform#133]
Hi,

I am on the latest build of OctoberCMS and I have added the appropriate key and secret for reCaptcha v2 (checkbox).

The "I am not a robot" captcha is correctly displayed on the form and I can check it, but when I submit the form I get the default captcha validation error message (default : "Google reCAPTCHA validation error!")

Not sure if I'm doing something wrong!

Regards

**Comment by jan-vince** [comment]
Hi,

I still do not use OC2, so I can’t test it. 

But be sure you have component inside layout or CMS page. 

Small Contact Form not work inside partial. 


Best regards,

Jan


< Ing. Jan Vince / webdesigner / +420 733 127 581 / www.vince.cz />

**Comment by kavishdahekar** [comment]
I do have the component and the form is rendered correctly and works if captcha is disabled!
Is there anywhere in the plugin code that could help me debug this?

![image](https://user-images.githubusercontent.com/3937361/150755392-d75734bf-2fb0-45af-a390-3057234ac23a.png)

**Comment by jan-vince** [comment]
All error are logged in System log - maybe there is some PHP modules disabled.

There is issue on this #124

**Comment by kavishdahekar** [comment]
`allow_url_fopen` is already turned on :(

**Comment by jan-vince** [comment]
And any other errors in October system log ?

**Comment by kavishdahekar** [comment]
None unfortunately.
I'll try debugging the form submission, see if something is going wrong there.

**Comment by jan-vince** [comment]
Can be a compatibility problem - I have not tested it with OC2.

You can add some `Log::debug()` in [component](https://github.com/jan-vince/smallcontactform/blob/85d824d887a9e788ef6825fafe61e13c31237880/components/SmallContactForm.php#L344).

**Comment by kavishdahekar** [comment]
Found the issue. Google reCaptcha does not support localhost testing anymore, if you want to test on localhost you need to explicitly add `localhost` to the allowed domains in the reCaptcha configuration. The allowed domains list does not accept `127.0.0.1`, so you have to use `localhost`.

I had already done this, but the plugin uses `$_SERVER['SERVER_NAME']` for recaptcha hostname validation here : https://github.com/jan-vince/smallcontactform/blob/85d824d887a9e788ef6825fafe61e13c31237880/components/SmallContactForm.php#L360

The issue is `$_SERVER['SERVER_NAME']` holds `127.0.0.1` on my localhost (using `php artisan serve`). When I overwrite it with `localhost` the captcha validation works.

I can raise a PR that checks if `$_SERVER['SERVER_NAME']` holds `127.0.0.1` and if yes it will use `localhost` in the `$recaptcha->setExpectedHostname` call.
