### ISSUE TITLE
Hardcoded jquery version in the component

### ISSUE THREAD

**Issue by mlieshout** [jan-vince/smallcontactform#143]
Hi,

Is there a reason for the hardcoded jquery version in the component?

$this->addJs('https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js');

Same goes for the bootstrap@3.3.7:

$this->addJs('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js');

According to Google Lighthouse, these components contain vulnerabilities.

**Comment by jan-vince** [comment]
Hi,

these just were up to date in time of plugin writing and I have tested plugin with them.

You can always use your own versions.

"Add assets" is optional and disabled by default. 

I will update these when I eventually switch to OC3.
