### ISSUE TITLE
How to output the checkbox value

### ISSUE THREAD

**Issue by AT-Mneme** [jan-vince/smallcontactform#147]
Hi Jan. We need to change the code to output the checkbox value in the Message.php file? 

The output only shows checkbox was checked(on), but it doesn't show the value of the field of name. 

![input-to-output-ContactForm](https://user-images.githubusercontent.com/110415107/190999465-f6e71b4d-d829-40ae-aa16-4310d94f2f54.png)

**Comment by jan-vince** [comment]
I do not use `value` attribute for checkboxes (not sure why after that long time :)

But when I use it in Twig (eg. mail template), I do check the value `on` and replace it with field label like `{{field.label}}`.
