### ISSUE TITLE
framework.extras 404 error

### ISSUE THREAD

**Issue by webmappsrl** [jan-vince/smallcontactform#151]
Hello, i am new to October CMS. I can not make this plugin work. After reading the readme i have activated 'Add assets' and 'Add Javascript assets' and put {% scripts %} tag under my form {% component "contactForm" %} but receive:
GET https://.../modules/system/assets/js/framework.extras.js net::ERR_ABORTED 404 (Not Found) 

Any help will be appreciated.

**Comment by webmappsrl** [comment]
I changed the name of the existing file: /modules/system/assets/js/framework-extras.js to /modules/system/assets/js/framework.extras.js the error is gone but no message was sent. the page reloaded with no notification. I have already configured my Mail SMTP option from backend. and i use The latest version of  the CMS 3.1.26

**Comment by jan-vince** [comment]
Hi,

this was prepared for October v1 and probably will not work in newer versions (as I do not use these options I haven't noticed).

If you do not need AJAX sending, this is not needed.

Be sure to have component definition placed in layout or CMS page. It will not work in partial!

PS: But you can put `{% component contactForm %}` in partial.

Start testing with AJAX option disabled in Contact Form settings.

**Comment by webmappsrl** [comment]
Thanks a lot for the quick answer. It worked by putting the Component Definition in my page instead of the partial.
