### ISSUE TITLE
Forgot to add fields - Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by maki3000** [jan-vince/smallcontactform#153]
Hello,

I just updated to the most recent version 1.6.

Unfortunately I'm getting following error, when going to the settings:
`Invalid argument supplied for foreach()`
`~/plugins/janvince/smallcontactform/models/Settings.php line 176`

I guess, this is because I filled almost everything out in the settings, but no fields. Do I need to purge the data or is there another way to solve this?

**Comment by jan-vince** [comment]
Hi @maki3000, what version of October do you use?

I will try to find and fix a problem.

**Comment by maki3000** [comment]
Hey @jan-vince 
I use the latest 2.1.x version.

**Comment by jan-vince** [comment]
I do not use OC2, I have skipped this version to OC3 (3.2).

I can't replicate your problem in clean OC3 install with Small Contact Form.

Try to remove plugin configuration from database and configure it again.

**Comment by maki3000** [comment]
I now removed the settings from the DB, cleared the cache and it works again. I added a field and some settings in the form tab, saved it and like this it is working perfectly.

Maybe you could add a validation so that user add one field for sure.

Thank you very much for the plugin!

**Comment by maki3000** [comment]
Hey,

I tried some validation options and because standart laravel array validation quickly becomes complicated, I thought you could add a `beforeSave` model event in plugins\janvince\smallcontactform\models\Settings.php

```
public function beforeSave()
{
        if ($this->value['form_fields'] === null)
        {
            throw new \ValidationException([
               'form_fields' => 'Please add at least one form field.'
            ]);
        }
}
```

I tested it in my OC 2.x instance and it saved with at least one field and without any it flashed the messase "Please add at least one form field.", which may be added to translations.

Sorry, I can't do a PR, because I unfortunately don't have the settings here.

**Comment by maki3000** [comment]
Hey,

I tried some validation options and because standart laravel array validation quickly becomes complicated, I thought you could add a `beforeSave` model event in plugins\janvince\smallcontactform\models\Settings.php

```
public function beforeSave()
{
        if ($this->value['form_fields'] === null)
        {
            throw new \ValidationException([
               'form_fields' => 'Please add at least one form field.'
            ]);
        }
}
```

I tested it in my OC 2.x instance and it saved with at least one field and without any it flashed the messase "Please add at least one form field.", which may be added to translations.

Sorry, I can't do a PR, because I unfortunately don't have the settings here.
