### ISSUE TITLE
Black- or whitelist IPs

### ISSUE THREAD

**Issue by maki3000** [jan-vince/smallcontactform#154]
Hello,
I guess, it's not possible to black- or whitelist IP addresses? 

I could look into that, if you want. I think, making two fields under the tab Antispam, saving them and checking the senders IP against it, is a think I could do.

Should I do a PR in the near future?

**Comment by jan-vince** [comment]
Not directly - when you allow IP testing in Settings, IP will be disabled after specified number.

No problem to merge it if you create PR.

**Comment by maki3000** [comment]
Hey! I just got the info, that we actually want to block IPs outside german speaking countries (DACH). So I thought, I'd rather create a plugin, that is extending yours, because we need a service like https://ip-api.com to get up to date IP information and this seems rather a specific option to me.

Of course I will publish my extension to GitHub, when I'm finished.

But I have two requests to you:
Could you please make `private $validationRules;` public? And is it possible to implement a `setFieldsValidationRules()` getter, so I'm able to overwrite `onFormSend()` in my class extension? 

Or do you think, there's a better option for that?

If you think it's helpful, I also could create a PR to add black- and whitelisting fields, but I think, extending your plugin is the better option.

**Comment by jan-vince** [comment]
Maybe adding your custom validation rule can be the option: https://docs.octobercms.com/1.x/services/validation.html#custom-validation-rules

You can than add the custom rule to any of the fields.

**Comment by maki3000** [comment]
Hey! It took me a while to figure out how to extend a plugin component. Here are more infos about it:
https://talk.octobercms.com/t/overwrite-plugin-method-with-own-plugin-class/1069

When done like this, of course this is not needed:
> Could you please make private $validationRules; public? And is it possible to implement a setFieldsValidationRules() getter, so I'm able to overwrite onFormSend() in my class extension?

I want to publish the extension on GitHub, when I'm finished...

**Comment by maki3000** [comment]
Hey! Here's the link to the repo of my extension:
https://github.com/maki3000/SmallContactFormExtension

I'm aware, that it is not that perfect, but it fulfills our intention of getting less spam mails, since we now only allow, for our only german page, sending from DACH area.
