### ISSUE TITLE
Antispam Google reCaptcha submits the form automatically

### ISSUE THREAD

**Issue by jannikholsten** [jan-vince/smallcontactform#159]
Hey, 
I've got a problem using the Antispam Google reCaptcha checkbox. Everytime I click the checkbox, it automatically submits the form. So basically the reCaptcha-check works as expected, but it shouldn't submit the form automatically after it got checked.
Thankful for any help.

**Comment by jan-vince** [comment]
Hi @jannikholsten I will look at this and let you know.

**Comment by jan-vince** [comment]
Hi @jannikholsten, this should be fixed in 1.63.1 (just released).

Thank you!

**Comment by jannikholsten** [comment]
Perfect, thanks for the quick reply 👍
