### ISSUE TITLE
Programmatically modify form posted content

### ISSUE THREAD

**Issue by hmsuchier** [jan-vince/smallcontactform#161]
Hi,
 Is it possible to modify posted form content (in the onStartx function for example), according to an (url) get parameter for example?
Thanks!

**Comment by jan-vince** [comment]
Sorry, there is no support for this in plugin (no events listeners). But I am open to any PR :)

**Comment by hmsuchier** [comment]
Thanks for your quick answer. No idea on how to add event listeners (new to October), but when i'll figure out, i'll consider a pull request!

**Comment by hmsuchier** [comment]
Rather than event listener, wouldn't it be interesting to fire an event somewhere on the `smallContactForm` component's `onFormSend` method?

**Comment by jan-vince** [comment]
I have never needed this but I have no problem to include such functionality (PR).
