### ISSUE TITLE
foreach() argument must be of type array|object, null given

### ISSUE THREAD

**Issue by justbobTN45** [jan-vince/smallcontactform#162]
foreach() argument must be of type array|object, null given

~/plugins/janvince/smallcontactform/models/Settings.php line 176

Getting the above error when I click on "Form Settings". Fresh install of October version 3.3.17 with PHP 8.2.6. No other plugins installed.

**Comment by jan-vince** [comment]
Looks like this problem #160 ?

I have just tested on fresh install - 3.3.17 + PHP 8.2.5 and no problem to access settings.

Start with cache clear or go to backend area > Updates > Manage plugins > check Small Contact Form and click on button "Select Action..." and click Reset plugin data.

**Comment by justbobTN45** [comment]
Clearing the cache and resetting the plugin data fixed the problem. Thank you for your help!
