### ISSUE TITLE
Plugin broke on first use

### ISSUE THREAD

**Issue by baggednismo** [jan-vince/smallcontactform#166]
Was just checking out the settings, options, etc. Last thing I did was go tot he form fields and added a new one. Didnt change anything but likely navigated away. Now im unable to access the plugin's settings. Likely a dupe of https://github.com/jan-vince/smallcontactform/issues/160

I did cache:clear and cleared in my browser. then reset plugin data. no luck though, still not working.
`ErrorException: foreach() argument must be of type array|object, null given in /var/www/albanyat.com/plugins/janvince/smallcontactform/models/Settings.php:176`

**Comment by jan-vince** [comment]
Sorry, I can't replicate this. What version of October and plugin do you use?

Removing and reinstall plugin solve this?

**Comment by baggednismo** [comment]
OctoberCMS: 3.4.11
SmallContactForm: 1.63.5

_Removing and reinstall plugin solve this?_ No, I have removed and reinstalled multiple times and tried clearing cache in different ways in between without success.

**Comment by jan-vince** [comment]
I am sorry, but I can't replicate this :(

But I have added an extra check for fields array in new version so this should not happen again.

If you can check this please let me know.
