### ISSUE TITLE
Email field problem

### ISSUE THREAD

**Issue by nvandendries1984** [jan-vince/smallcontactform#167]
If I send an email using the standard form, the email address is not stored in the database and is not processed further.
![image](https://github.com/jan-vince/smallcontactform/assets/45072919/464fb11d-2bbe-4076-a9f3-e99cdf7d3242)
![image](https://github.com/jan-vince/smallcontactform/assets/45072919/ef2f6180-19f8-4364-8bf2-ddb96a6f5912)

**Comment by jan-vince** [comment]
Please add a screenshot of email field from backend.

**Comment by nvandendries1984** [comment]
I removed the preset fields en configured new ones, after binding the field to the Database columns it is working without problemes.
