### ISSUE TITLE
An idea that supports multiple forms

### ISSUE THREAD

**Issue by ZhiweiWu0425** [jan-vince/smallcontactform#171]
A new idea is to create a setting table, where each setting record will establish a new form to meet the diverse form requirements of a large website.

This feature has been implemented on my website a long time ago. Due to the tight deadline given by the client, my code was not written ideally. If you would like to spend a few hours organizing my code and integrating it into the plugin, I can provide you with my code
![image](https://github.com/jan-vince/smallcontactform/assets/89636889/c97e6b97-94c7-4ade-938b-9557add2eb79)

**Comment by jan-vince** [comment]
Hi,

Small Contact Form was meant to be really small and simple so I will not implement this.

Thanks anyway !
