### ISSUE TITLE
Hey, when submitting the form I get following javascript error in debug

### ISSUE THREAD

**Issue by freeyland** [jan-vince/smallcontactform#172]
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLFormElement.<anonymous> (validate.js:24:41)
(anonymous) @ validate.js:24

==>  line 24 corresponds to  thisForm.querySelector('.loading').classList.add('d-block');

Looks like loading container is missing in html template

**Comment by jan-vince** [comment]
Hi @freeyland,

what is your setup? Versions of OC, Contact form plugin, how do you use the plugin (where is component)?

**Comment by freeyland** [comment]
Hi @jan-vince 
October 3.5.14
The component is inside a partial

**Comment by jan-vince** [comment]
Try to put your component in layout or CMS page.

In partial you can call it with {% component 'contactForm' %}, but component definition should not be placed here.
