### ISSUE TITLE
Its not compatible with October Version 3.6.3

### ISSUE THREAD

**Issue by jannikholsten** [jan-vince/smallcontactform#174]
Hey, 
October changed the syntax for mail templates in Version 3.6.3. Its shorter now. Currently it throws an error because in Settings.php it´s still this syntax:

`'janvince.smallcontactform::mail.autoreply' => 'janvince.smallcontactform::lang.mail.templates.autoreply',`

correct would be:

`'janvince.smallcontactform::mail.autoreply',`

Please fix this as soon as possible. Take a look in the in the Release notes [https://octobercms.com/support/article/rn-37](https://octobercms.com/support/article/rn-37)

Thanks.

**Comment by jan-vince** [comment]
Hi,

I am not using 3.6 yet and I will wait until that many issues in this release will be solved.
