### ISSUE TITLE
Form in %placeholder%

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallcontactform#18]
Had problems with 
> AJAX handler 'contactForm::onFormSend' was not found.

because the component was placed in a partial. I created a placeholder in the layout with the `contactForm` component and called the placeholder in the partial.

Form works and sends data in the partial, but does not in a page. My question is if this is the correct way to place the component? Is there any security issue because of the placement method?

**Comment by jan-vince** [comment]
Can you post here code of how you use it with partial?

**Comment by zlobec** [comment]
So,

the component is placed in the layout page with component included in the layout: 
```
{% put contactForm %}
 {% component 'contactForm' %}
{% endput %}

{% page %}
```
Later its called in the `{% partial 'footer' %}` and in page "Contact" as: `{% placeholder contactForm %}`

When in partial, the form works O.K., but when in page, it does not. Blank output. To make it work I put another component in the page and called it standalone not as placeholder.

**Comment by jan-vince** [comment]
I believe that components can't be used inside of ````{% placeholder %}```` tag. [It's intended for text or html](https://octobercms.com/docs/markup/tag-placeholder#custom-placeholder-attributes).

What is your idea behind a placeholder? Why do you use it?

**Comment by zlobec** [comment]
I was testing some other form plugin before and because I had to implement it on more locations on the page, I simply put in the placeholder (didn't read thoroughly the placeholder manual) and call the placeholder later on seperate locations (page, partials... etc). 

But how come the component works in the partial then?

**Comment by jan-vince** [comment]
Components do work inside of partial, but [AJAX calls are not supported](https://octobercms.com/docs/cms/partials#life-cycle-limitations). This is why you get the error.

Other problem is that I have never thought about multi-form usage, so some parts are "hard coded".

*But I will update my plugin to support multiple use!*


Than I think you should add multiple components to a page with different aliases to get this all work. 

Like this:

````
title = "form"
url = "/form"
layout = "default"
is_hidden = 0

[contactForm contactForm1]

[contactForm contactForm2]

==

<h1>My first contact form</h1>

{% component 'contactForm1' %}


<h1>My second contact form</h1>

{% component 'contactForm2' %}
````

**Comment by jan-vince** [comment]
I have just published updated version that support more than one occurence of contact form.

Tested with code I have sent in higher post...
