### ISSUE TITLE
Google reCaptcha support

### ISSUE THREAD

**Issue by zooks** [jan-vince/smallcontactform#23]
Please add reCaptcha support to the Antispam tab.

**Comment by jan-vince** [comment]
Hi, I have this on my todo list.

But I do not use reCaptcha on my web sites so it doesn't have much priority.

Feel free to send a PR for this I will gladly review it!

**Comment by jan-vince** [comment]
Hi @zooks,

I have finally had a time to add reCaptcha to my Contact Form plugin.

It is available in 1.6.0 version.

Thanks for and issue.
