### ISSUE TITLE
Ajax is not working

### ISSUE THREAD

**Issue by zooks** [jan-vince/smallcontactform#24]
I set "Enable Ajax" at plugin settings. And my page reloads while sending form.

**Comment by jan-vince** [comment]
Have you also checked "Enable Assets" and also "Add JavaScript assets" ?

If you don't add October Ajax framework by hand or by checking this option, AJAX will not work.

You can look in [README.md file](https://github.com/jan-vince/smallcontactform) for more info.

**Comment by zooks** [comment]
Yep, JavaScript was enabled. I rechecked my code and I figured out I forgot to set
`{% scripts %}` in my layout. Now it works perfectly!
