### ISSUE TITLE
Email tpl uses field names instead of labels

### ISSUE THREAD

**Issue by zooks** [jan-vince/smallcontactform#25]
For example here: janvince.smallcontactform::mail.notification
`{{ key }}` must be a label.

**Comment by jan-vince** [comment]
Sure, it could be a label but I wanted to use the field name here.

I can add a setting for this to use labels instead of names.

I will add this to my todo list.

*Feel free to send a PR if you need this urgently.*

**Comment by jan-vince** [comment]
Hi @zooks,

I have just published a new version of this plugin where ````fieldsDetails```` array is available in all email templates.

So you can use it like this if you need labels:

````
{% for field in fieldsDetails %}

{{ field.label }}: {{ field.value }}

{% endfor %}
````
----

I have updated default *autoreply* mail templates for reference how to use fieldsDetails array. Notification templates remain same.
