### ISSUE TITLE
Multiple Send-To Email Address Templates

### ISSUE THREAD

**Issue by abass** [jan-vince/smallcontactform#26]
Hi there,

On our site and many clients, we usually have at least 2 separate contact forms. 1 is usually just a general "contact us - sales" form and the other is generally a "support" form.

We need the inquiries sent from the "sales" form to be sent to sales@company.com while the support goes to support@company.com (so that it can be properly filed and a ticket can be created in a help desk).

The information collected here is also slightly different for each form. Different information requested for Support form versus a Sales request form.

Here is a great implementation of a different contact form that has since been abandoned (but one of the top selling contact forms on OctoberCMS.)

![image 2017-08-16 at 1 57 00 pm](https://user-images.githubusercontent.com/5505994/29377810-f43e34c0-828a-11e7-8863-84b5f7b9ec97.png)

![image 2017-08-16 at 1 57 21 pm](https://user-images.githubusercontent.com/5505994/29377827-ffaafc4e-828a-11e7-91cf-18bbf77fd774.png)

![image 2017-08-16 at 1 57 41 pm](https://user-images.githubusercontent.com/5505994/29377836-068d9c1a-828b-11e7-9d38-06268ccc13da.png)

![image 2017-08-16 at 1 57 56 pm](https://user-images.githubusercontent.com/5505994/29377843-0d75519e-828b-11e7-8764-6b9cddc782b1.png)

**Comment by jan-vince** [comment]
Hi Alex,

if I understand right you need two separate forms with different fields and email templates.

But I want to keep my plugin as simple as possible so I don't think I will ever support more than one form setup. Maybe Renatio's [Form Builder plugin](https://octobercms.com/plugin/renatio-formbuilder) is more suitable for your use case ?

On the other hand, I was thinking about adding more component parameters so anyone can "fine tune" each instance of Contact form.

From what I'm thinking about is:

* allow email addresses override (reply and notification) and templates
* disable/hide some form fields

So the component setup would look like this:

````
[contactForm]
replyEmailAddress = "some@domain.com"
replyEmailTemplate = "my.custom.reply.template"
notificationEmailAddress = "other@domain.com"
notificationEmailTemplate = "my.custom.notification.template"
disableFields = "phone|message"
````

I think this would allow "semi" multi form setup.

**Comment by abass** [comment]
Hi Jan,

Thanks for the reply! Completely understand where you are coming from. The Form Builder that you linked to could possibly work in some regard. I do like your layout a lot though.

I think the component idea you have is very interesting. Feels easy enough to make tweaks and deeper functionality without too much additional work or complexity. That would be great!

**Comment by jan-vince** [comment]
Hi Alex,

I have made a new version of contact form with some support for multi form setup.

Now you can override email addresses and templates for notification and autoreply and hide fields.

Detailed HOWTO is in documentation (at the end).

*I would appreciate if you can test it (edgeUpdates must be enabled in your OctoberCMS) and send me some info :)*

**Comment by abass** [comment]
So stoked! Awesome work man! I'll be checking it out soon - just bogged down with a bit of client work at the moment! Very excited though!

Quick question to this, is there any way to set it such that the "reply-to" field is the person submitting the form? I can't seem to figure out a way to get that working. But when we get an email in for support and/or sales, it sends from our site (notifications@ourcompany.com), really wish we could hit reply (and it would just pull the reply-to) the email address entered in on the form by the potential customer (if it could pull the name that'd be awesome too).

I'm noticing that as a major lacking feature in the way that emails work. Was wondering if that is someone on the plugin's end? Or October's end?

Cheers buddy! Definitely looking forward to checking it out!

**Comment by jan-vince** [comment]
Hi Alex,

I had this on my todo list for some time so I have added it right now - in version 1.5.3 you can check an option under Email > Allow notification that will replace default FROM address and name with those filled in contact form.

*Email (and optionally Name) field has to be mapped in Column mappings.*

1.5.3 version is production now as I have tested it on several of my sites.

*But if you find a bug please let me know ... :)*

**Comment by abass** [comment]
Killer job! You're awesome! Keep up the phenomenal work! I'll definitely check this out soon! Cheers!
