### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by hodo7** [jan-vince/smallcontactform#27]
Hi, first off, like this plugin so far, it's very easy to use!  I'm having one issue though, and it may be something dumb I'm overlooking since I'm new to OctoberCMS.

I have a simple contact form and the form is sending and submissions are being logged in the back end, but no emails are reaching my email inbox.

In Mail Configuration I have the Sender field filled out and the Mail Method is set to PHP Mail (I tried other methods and they didn't work, either).  In the plugins options, under the Email tab I have Allow Notifications set and the Send Notification Email field filled out. Admin is the only user and email is set there as well.

Any help is appreciated, but apologies ahead of time if this was a simple fix I was too oblivious to find, haha.

**Comment by jan-vince** [comment]
Hi and thanks!

Check an error log if there is something starting with ````SMALL CONTACT FORM:````

What is your OctoberCMS version and language?

**Comment by hodo7** [comment]
I'm so sorry, I just discovered the issue was tied to me trying to work on it locally, but on the production server it sends out emails fine, so something is up with my local set up.  Thank you so much for your help, though!

**Comment by jan-vince** [comment]
No problem - hope you will solve it!
