### ISSUE TITLE
Having Difficulties Configuring

### ISSUE THREAD

**Issue by abass** [jan-vince/smallcontactform#28]
I am running into a lot of difficulties trying to get this form to work. I'm used to other forms being a bit more descriptive like:

```
<form role="form"
      data-request="{{contact}}::onContactSent"
      data-request-update="'{{contact}}::confirm': '.confirm-container'"
      data-request-success="$('.form-groups').slideUp(1000)">
</form>
```
and the steps being more clear into "how" you are supposed to configure the form. I want to use all of my own custom fields (I have the form actually created on my site right now http://cyberbytes.co/support but can't figure out).

I have read through the docs about 3-4 times now and this is the 4th or 5th contact plugin I have used and haven't had trouble with the other ones. They had the ability to just drag in the code snippet for the form though which made it very straightforward. I'm stuck right now and burning a lot of time trying to figure out how to get this working :/

Not sure if you have like a live example anywhere that we can inspect the code to see exactly what HTML you have written out in order for your plugin to grab the data because that would help a LOT.

Thanks! (:

**Comment by jan-vince** [comment]
Hi @abass,

if you are trying to add select boxes to my plugin, it won't work.

I do not support it right now and you cannot add them manually as my plugin is checking for configured fields and will throw away anything else in POST data.

It would not be very difficult to add support for select boxes to my plugin, but right now I have no free time :(

You can post PR or will have to wait to my code.

**Comment by jan-vince** [comment]
Hi @abass, support for dropdown is in version 1.20.

Best regards,

Jan
