### ISSUE TITLE
Form gets posted, but nothing is saved to the database.

### ISSUE THREAD

**Issue by domagoj03** [jan-vince/smallcontactform#29]
I'm sorry if this is sort of broad spectrum issue as 'anything can be wrong', but maybe I missed something obvious... 

After posting the form, I get 200 OK response for the POST route with proper headers, however, no messages are written in the database, hence none returned in the dashboard. 

More data:
- not being redirected to the specified url (/)
- no thank you message
- only using javascript assets
- fields included - fullName, message, email - all properly mapped under the column mapping
- enabling AJAX - 

> AJAX handler 'contactForm::onFormSend' was not found.

I installed the plugin directly from the CMS backend and added this minimal configuration. There is a chance Mail Configuration is not working properly, but I don't think this should interfere with storing messages.

**Comment by jan-vince** [comment]
Hi,

maybe you are trying to run the plugin inside of a partial ?

If so, try to put plugin's component inside of a page or a layout instead.

*Partials has a [limited AJAX functionality](https://octobercms.com/docs/cms/partials#life-cycle-limitations).*

**Comment by domagoj03** [comment]
Perfect, that fixes it for me. Although it's probably not a fix for people whom need it inside of a partial, for whatever the reason. 

Thanks @jan-vince for the very quick response.

**Comment by jan-vince** [comment]
Actually you can use the form's component inside of a partial but component's definition has to be in layout or page that includes that partial.

I am using it this way.

*The only problem here is an AJAX response that has to be prepared before partial is taken in a page life cycle.*

Best regards,

Jan

**Comment by ghost** [comment]
I've added a form to a partial (footer) and the footer appears on all pages. I added the form component to all my layouts. The form displays in the footer. I can submit the form, but it does not go to the page that I've set in the redirect. It also does not save to the database (well, i cannot see it on the message list). What am i doing wrong?

**Comment by ghost** [comment]
I got it to work. Remove component from partials. Add component to all page layouts where needed. In footer partial you can include {% component 'contactForm' %} and it will work.
