### ISSUE TITLE
Double Emails with AJAX enabled

### ISSUE THREAD

**Issue by xillonz** [jan-vince/smallcontactform#30]
As the title says, I am getting two of every form submission as long as "Enable AJAX" is checked. Otherwise seeming to work just fine. Any thoughts, maybe just a configuration issue?

**Comment by jan-vince** [comment]
Try to check if you don't have a Form component definition included in layout and also in page or partial.

**Comment by xillonz** [comment]
When setting up, I did have to move the contact form out to the layout to get it to work. But double checking everything, it looks like its only defined once in the layout and no where else.

**Comment by jan-vince** [comment]
So maybe framework JS files are added twice.

If you have checked **Add JavaScript assets** in Contact form settings, try to uncheck it and test form send.

*With this setting checked, Contact form adds OctoberCMS framework JS files - and you have probably added this manually in your layout. If these are included twice, all AJAX calls are executed twice.*

**Comment by xillonz** [comment]
Yup that was it. Thanks for the help!

**Comment by jan-vince** [comment]
You are welcome :)
