### ISSUE TITLE
Found a non-defined field in sent data!

### ISSUE THREAD

**Issue by danhumphrey89** [jan-vince/smallcontactform#37]
Setup a standard contact form with four fields:

- Name: type: text
- Email type: email
- Number type: text with numeric validation
- Message type: text

All data comes through and gets saved in the database except for the email field which returns the following error:

SMALL CONTACT FORM WARNING: Found a non-defined field in sent data! Field name: Email_Address and value: test@test.com

Any idea?

Thanks,
Dan

**Comment by jan-vince** [comment]
Try to use "email" as a field name (or other simple and lowercase name).

Maybe there is a problem with upper case.

I can't test it myself as I don't have enough time right now - but let me know where this helps or not.

Thanks for issue!

Best regards,

Jan
