### ISSUE TITLE
Add project to Packagist

### ISSUE THREAD

**Issue by LukeTowers** [jan-vince/smallcontactform#39]
Great job on this plugin @jan-vince!

Could you add it to Packagist so that we can add it to our October instances with 
`"jan-vince/smallcontactform": "dev-master"` added to our composer.json files?

**Comment by jan-vince** [comment]
Hi @LukeTowers,

I have never used Packagist but will look at it and submit Contact form there!

**Comment by LukeTowers** [comment]
Awesome, thanks!

**Comment by LukeTowers** [comment]
@jan-vince ping

**Comment by jan-vince** [comment]
Hi @LukeTowers I have this on my ToDo list but as I have never used Packagist I have to read docs to understand how it works.

If you need this fast maybe you can help me with ````composer.json```` creation and testing?

**Comment by LukeTowers** [comment]
The composer.json file is fine as it is, you just have to signup for an account on Packagist.org and then add this repository to your account, and optionally (ideally) setup their webhook with this repository's settings so that it auto updates packagist whenever you make a commit.

**Comment by jan-vince** [comment]
Hi @LukeTowers, Small Contact Form is on packagist.org: https://packagist.org/packages/janvince/smallcontactform

Thanks for help and reminders :)
