### ISSUE TITLE
Bootstrap 4 support?

### ISSUE THREAD

**Issue by boris61** [jan-vince/smallcontactform#40]
Any chance of this happening? Custom validation has changed in Bootstrap 4 so it doesn't work here, no matter what I try I always get browser default messages.

Best regards,
Boris

**Comment by jan-vince** [comment]
I am still waiting for Bootstrap 4 stable - but it will probably not happen any time soon :)

What exactly doesn't work for you? Can you post me a screenshot of it?

**Comment by boris61** [comment]
Attaching screenshots of settings page and how it looks on the page.

![contact-form-01](https://user-images.githubusercontent.com/17053039/35808070-fa990fac-0a84-11e8-8791-07bc327cb17e.png)
![contact-form-02](https://user-images.githubusercontent.com/17053039/35808072-fd3e891c-0a84-11e8-9275-32e0252599c7.png)

**Comment by jan-vince** [comment]
Hi @rizbo61,

I think that this is a browser native popup and is displayed because of there is a ````required```` attribute on ````input```` tag.

As far as I know this cannot be disabled even when JavaScript is off.

You need to disable this popups but still validate required fields on server side?

Do I understand it right?

**Comment by boris61** [comment]
It is browser native, that's what I said in the first post. I don't really need to validate it on server side, I just want to style error messages differently. I don't understand why it doesn't add 'help-block' spans if I have it enabled in plugin administration.

**Comment by jan-vince** [comment]
Can you post here a fragment of form field HTML code so I can see how you want it to be prepared by Small Contact plugin?

**Comment by boris61** [comment]
It's plugin default. I didn't change anything, just enabled Field validation and entered my messages in plugin administration. The way I understand it, this piece of code 

`if(!empty($this->postData[$fieldSettings['name']]['error'])){
        $output[] = '<small class="help-block">' . Settings::getDictionaryTranslated($this->postData[$fieldSettings['name']]['error']) . "</small>";
      }`

should add a help-block with validation message, but for someone reason it doesn't happen, I just get a browser default popup.

**Comment by jan-vince** [comment]
Ok, I see it now.

I have added to new features to plugin:

#### Option to disable browser built-in validation

If checked, ````novalidate```` attribute will be added to form.

![snimek obrazovky 2018-02-06 v 14 40 45](https://user-images.githubusercontent.com/1104383/35862567-749bac5c-0b4c-11e8-93bb-6f49b8ef46db.png)


#### Added ````is-invalid```` class to field that has error.

This will make an error field displayed red (if Bootstrap 4 is used).

*But right now there is no full support for Bootstrap 4!*

You will have to add your own style for ````invalid-feedback```` class like:

````css
form .invalid-feedback {
  display: block;
  color: red;
}
````

for error message to correctly been shown in Bootstrap 4!


Is this what you have needed?

**Comment by boris61** [comment]
Kind of, but it won't really work properly out of the box because Bootstrap 4 don't have 'has-error' classes anymore. But anyway, I made some changes to plugin so it now works how I wanted it to. Thanks for help.

**Comment by jan-vince** [comment]
Right now I do not fully support Bootstrap 4, so it will not work out of the box.

But I will add it as soon as I have some project on Bootstrap 4.

Thanks for issue!

Best regards,

Jan
