### ISSUE TITLE
I can't uses

### ISSUE THREAD

**Issue by darwinmanchola** [jan-vince/smallcontactform#41]
I have this error.
El manejador de AJAX 'contactForm::onFormSend' no se encuentra.

**Comment by jan-vince** [comment]
Hi @darwinmanchola,

I don't speak spanish, but it looks like you are trying to add component to partial. Isn't it ?

Try to put component definition to layout or page.

Let me know.

**Comment by jan-vince** [comment]
Hi @darwinmanchola have managed to get the plugin worked?

**Comment by giedrius-a-15004** [comment]
Hi, I get the same error. My one-page site is based on partials. Maybe you have a way to workaround it without rewriting entire site to pages?

**Comment by jan-vince** [comment]
Hi @kalabok123, it is important to have component definition in layout or CMS page to make AJAX work.

Sorry for late answer.
