### ISSUE TITLE
Plugin logs error when reCAPTCHA enabled

### ISSUE THREAD

**Issue by LukeTowers** [jan-vince/smallcontactform#43]
The plugin will currently log an error on submission if reCAPTCHA is enabled because it thinks that it is an undefined field in the form submission dataset. Exact error message is `SMALL CONTACT FORM WARNING: Found a non-defined field in sent data! Field name: g-recaptcha-response and value: `

**Comment by jan-vince** [comment]
Hi @LukeTowers and thanks for issue - I will fix it and send a version.

**Comment by jan-vince** [comment]
Fixed in 1.9.2 :)

Best regards,
Jan

**Comment by LukeTowers** [comment]
Thanks @jan-vince!
