### ISSUE TITLE
Error message after success send.  

### ISSUE THREAD

**Issue by weaswa** [jan-vince/smallcontactform#45]
Error message still appear after successful form send. 
![1](https://user-images.githubusercontent.com/22051620/36395823-ca6ceb9c-15c3-11e8-9669-60ab38623c06.jpeg)

**Comment by jan-vince** [comment]
Hi @vwvva,

thanks for issue. I will look over this and let you know!

*I am using built in Flash message mechanism that keep last message and this is probably cause of this.*

Best regards,
Jan

**Comment by weaswa** [comment]
Thanks a lot, your plugin is greate. 
I tried to fix this via flash assets, but no luck. 
And probably not the best place to ask, but what do you recommend for `<select>` form implementation? Cause now i using extremely goofy solution with simple js and hidden input in which I address data from the option.

**Comment by jan-vince** [comment]
Thanks but this is just a small plugin.

I have a todo to implement select box and I was waiting for a project when it will be needed - but there was none to this time.

I will try to add a select box soon :)

**Comment by jan-vince** [comment]
Hi @vwvva,

I have added dropdown support some time ago and now a Flash messages problem should be fixed in version 1.22.0.

Thanks for your issue!
