### ISSUE TITLE
Send info about page

### ISSUE THREAD

**Issue by vsamal** [jan-vince/smallcontactform#46]
Hi,

is there any option how to send in email additional information about page? 
The form is placed on all articles page and i need send with the form current page title and page URL.

I tried use:
{% component 'myForm' form_description' = 'page title and url' %}

but i can not add variable form_description to the mail template - only on backend list.

any idea how to add information about the page and article to the email?

thanks

Vaclav

**Comment by jan-vince** [comment]
Hi @vsamal 

I have added these fields to email templates and it is ready in 1.13. version.

You can access them with ````{{fields.form_alias}}```` and ````{{fields.form_description}}````.

Give it a try and let me know if it works for you :)

Best regards,

Jan

**Comment by vsamal** [comment]
Thank you, works very well, great job!

Vaclav

**Comment by jan-vince** [comment]
You are welcome :) 

And thanks for the issue!
