### ISSUE TITLE
Fix for Drivers plugin errors on PHP 7.2 using mailgun

### ISSUE THREAD

**Issue by firemankurt** [jan-vince/smallcontactform#47]
See https://github.com/octoberrain/drivers-plugin/pull/5#issuecomment-386941832
for a fix when using Mailgun and PHP 7.2

smallcontactform requires octoberrain.drivers when using Mailgun as sender but this will throw an error with PHP 7.2 

    "ErrorException: count(): Parameter must be an array or an object that implements Countable in (...)/drivers/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:67"

The error was fixed in  guzzle 6.3.3 but octoberrain.drivers only goes up to guzzle 6.2.0 because of flysystem-rackspace requirements.  So removing flysystem-rackspace from the composer.json allows update to go to  guzzle 6.3.3

**Comment by jan-vince** [comment]
Hi @firemankurt, can you post s PR to address this? 

As I do not use Mailgun I can't give this issue any time soon :(

**Comment by firemankurt** [comment]
This is not actually caused by your plugin.  It is an issue in  octoberrain.drivers plugin.
I posted here because users may see the error appear for the first time after installing your plugin and using Mailgun as the transport method.

I wanted others to know the root source of the issue is not your plugin and also lead them toa a way to eliminate the issue by modifying the composer.json file inside  octoberrain.drivers plugin and then running "composer update" on  octoberrain.drivers plugin.

So you do not have anything to fix unless you want to add your own composer.json and Mailgun driver.  Hopefully octoberrain.drivers plugin will be updated to allow Guzzle 6.3.3 soon.  This would eliminate the need to do any modification by end users.

**Comment by jan-vince** [comment]
Ok, thanks for explanation!
