### ISSUE TITLE
reCAPTCHA is not working

### ISSUE THREAD

**Issue by kvlsky** [jan-vince/smallcontactform#48]
I am using invisible version of reCAPTCHA and getting this kind of error:
`ReCAPTCHA couldn't find user-provided function: contactForm::onFormSend`
when trying to send request (clicking SEND button)

      $output[] = '<button type="submit" data-sitekey="6Ldf9FUUAAAAAFEhx3nu-K2A807YBisJxf3-VGRK" data-attach-loading data-callback="contactForm::onFormSend" class="g-recaptcha oc-loader '
          . ( Settings::getTranslated('send_btn_css_class') ?
              Settings::getTranslated('send_btn_css_class') : e(trans('janvince.smallcontactform::lang.settings.buttons.send_btn_css_class_placeholder')) ) . '">';

**Comment by jan-vince** [comment]
Hi @kvlsky, Contact form is using classic version of reCaptha and I have not tested it with invisible version yet.

But feel free to send a Pull request and I will review it ASAP.

**Comment by kvlsky** [comment]
The problem is, that it works great with another project. Could it be caused by later version of OctoberCMS in current project?

**Comment by jan-vince** [comment]
@kvlsky 

I don't think so - I'm using latest builds and also testing on the development branch (edge updates).

How about test your web with classic reCaptcha v2 key and then try invisible?

Any errors in JavaScript console?

**Comment by kvlsky** [comment]
@jan-vince it was just a problem with my server, thank you 😉
