### ISSUE TITLE
Sending notification email

### ISSUE THREAD

**Issue by piotrkrych2** [jan-vince/smallcontactform#49]
Hi,
I have app on PHP 7.2.2.
In `plugins/janvince/smallcontactform/models/Message.php` file is:
```
    public function sendNotificationEmail($postData, $componentProperties = [], $formAlias, $formDescription){

    ...
        if(!empty($componentProperties['disable_notifications'])) {
            return;
        }
```
I added `Log::error('SMALL CONTACT FORM ERROR: ' . var_export($componentProperties, true));
` to check what is in `$componentProperties` and this is result:
```
[2018-06-04 08:55:39] production.ERROR: SMALL CONTACT FORM ERROR: array (
  'form_description' => NULL,
  'disable_notifications' => 'false',
)  
```
As we know `'false' !== false` and that's why this condition is always true.
Fix it please.
All best.

**Comment by jan-vince** [comment]
HI @piotrkrych2 , are you sure about this?

When I dump ````$componentProperties```` while sending form I get this:

````
array:2 [▼
  "form_description" => null
  "disable_notifications" => false
]
````

Testing with ````dump(!empty($componentProperties['disable_notifications']))```` will result in ````true```` - that means notifications won't be sent.

*````Log::error```` method probably add those slashes while converting array.*


I am on PHP 7.1.8 so I can't test it on 7.2 right now, but will keep this in my todo list and check it later.

**Comment by piotrkrych2** [comment]
I'm confused.
If `$componentProperties['disable_notifications'] === false`, result should be `false`.
If `disable_notifications` is set to `false` it means notifications should send! 
If set to `true` - then notifications shouldn't send. 
Am I right?
```
php > var_dump(!empty(false));
bool(false)
php > var_dump(!empty('false'));
bool(true)
php > $componentProperties = ['disable_notifications' => false];
php > var_dump(!empty($componentProperties['disable_notifications']));
bool(false)
php > $componentProperties = ['disable_notifications' => 'false'];
php > var_dump(!empty($componentProperties['disable_notifications']));
bool(true)
```

**Comment by jan-vince** [comment]
Hi @piotrkrych2 

I am using this test in my code: 

````
        if( !empty( $componentProperties['disable_notifications'] ) ) {
            return;
        }
````

This test will be true if ````$componentProperties['disable_notifications'] == true````.

**Comment by piotrkrych2** [comment]
Where `disable_notifications` is set? On my code (or db) string is set to that index, and that is my bug.

**Comment by jan-vince** [comment]
It is get from component properties.

This is used to be able to disable notifications for specific form on component level.

You can enable/disable notifications globally, but if enabled, you can control this on component itself - for each form you can set different notifications setting.
