### ISSUE TITLE
How do I add custom classes to the form elements

### ISSUE THREAD

**Issue by wertykid** [jan-vince/smallcontactform#50]
Hello, as the title suggests, I want to add HTML classes to the form elements. How do I do that? 
Thanks for your response.

**Comment by jan-vince** [comment]
Hi @wertykid 

you can set your own classes in form setting (Settings > Small Contact Form).

![snimek obrazovky 2018-06-25 v 10 55 00](https://user-images.githubusercontent.com/1104383/41840626-85c17ee4-7866-11e8-849b-7a70bf024359.png)
![snimek obrazovky 2018-06-25 v 10 55 15](https://user-images.githubusercontent.com/1104383/41840632-87d634fe-7866-11e8-9079-4ffd27d8d938.png)
