### ISSUE TITLE
Flash messages errors

### ISSUE THREAD

**Issue by angay9** [jan-vince/smallcontactform#51]
Hi Jan, thanks for a great plugin.

I have 2 issues when using it with ajax:

1. When I send an empty form and validation errors appear along with the danger message on top of the form. And then if I fill in the fields correctly, the success message appears on top of the form, but the error message doesn't disappear.

2. If I submit a form and validation errors appear (using ajax) and then reload the page, the error message on top of the form stays and I have to reload the page once again to make it disappear.

Thanks,
Andriy

**Comment by jan-vince** [comment]
Hi @angay9 I know about the problem with flash messages.

*There is already an issue about this: #45*

I will look at this and try to fix it as soon as I have some time.

Thanks for the issue!

**Comment by vardash0131** [comment]
maybe whit "Session::invalidate();" to the end of method onFormSend()

**Comment by jan-vince** [comment]
Hi @vardash0131 and thanks for pushing me :)

I have used `Session::forget()` to empty used flash messages.

Try it in version 1.22.0.
