### ISSUE TITLE
How to use with Static Pages?

### ISSUE THREAD

**Issue by FelixINX** [jan-vince/smallcontactform#52]
Hi!

First of all, thank you for your fantastic plugin.

I would like to use your plugin inside a Static Page. My initial idea was to add it as a partial, but it dosen't work with October CMS AJAX limitations.

Do you have any idea how I could use your plugin?

Thanks!

**Comment by jan-vince** [comment]
Hi @FelixINX,

the trick is to insert component definition (````[contactForm] ...````) inside a layout of your static page.

````{% component contactForm %}```` can be than inserted in layout or partial.

This way AJAX will be handled by layout.

Give it a try and let me know!
