### ISSUE TITLE
verify email validation rule add

### ISSUE THREAD

**Issue by DikshaAhuja95** [jan-vince/smallcontactform#53]
how to customize the plugin for adding new validation rules and messages.

**Comment by jan-vince** [comment]
Hi @DikshaAhuja95 

only supported validation rules are available.

What rules do you need?

**Comment by DikshaAhuja95** [comment]
Hi,

I want validation rule --- "Same"   for the field Email and Verify Email.

**Comment by jan-vince** [comment]
Hi @DikshaAhuja95,

this is possible from version 1.19 with validation rule `custom` like this:

![snimek obrazovky 2018-11-29 v 15 39 07](https://user-images.githubusercontent.com/1104383/49229081-0dda2900-f3ed-11e8-9761-cd2cfae028d9.png)
