### ISSUE TITLE
how to add dropdown field with option values from backend 

### ISSUE THREAD

**Issue by DikshaAhuja95** [jan-vince/smallcontactform#54]
Thanks for the great plugin!!

how to add dropdown field with option values in field type from backend which shows on frontend and submit values

**Comment by jan-vince** [comment]
Hi @DikshaAhuja95 I haven't implemented this yet as I have never needed dropdown on my projects.

I have this in my todo list but feel free to send a PR to add this feature!

**Comment by jan-vince** [comment]
Hi @DikshaAhuja95, this is possible from version 1.20.
