### ISSUE TITLE
Dynamic redirect page

### ISSUE THREAD

**Issue by fredec** [jan-vince/smallcontactform#56]
Is there a way to change the redirect page depending on the slug, for example? Thanks!

**Comment by jan-vince** [comment]
Hi @fredec, not now.

What do you need this for? What is your use case?

**Comment by fredec** [comment]
Thanks jan-vanice for your answer!

I'd like to redirect depending on the slug because I want to use the "thanks page" with a link where the user could download some ebook, for example. With many ebooks I could use the same thanks page, where using the SLUG to get the right ebook I would change just the URL to download the file.

make sense? Or is there a better way to do it?

**Comment by jan-vince** [comment]
Hi @fredec, I will add this to my todo list.

I can add a redirect page URL right into component's properties, so you will be able to change it by passing URL in component call like `{% component contactForm redirectUrl = "/download/12345" %}`.

Is this what you are looking for?

**Comment by fredec** [comment]
This could be perfect!!! Thanks, it's going to be really helpful.

**Comment by jan-vince** [comment]
Hi @fredec 

I am terribly sorry for such delay, dynamic redirection is now supported by Small Contact Form.

Best regards,

Jan
