### ISSUE TITLE
Spam messages

### ISSUE THREAD

**Issue by gergo85** [jan-vince/smallcontactform#57]
I got more spam email:
![spam](https://user-images.githubusercontent.com/2959112/44264397-bc81a180-a222-11e8-8432-8544c0179c1f.JPG)

Do you plan to add a spam filter?

**Comment by jan-vince** [comment]
Hi @gergo85, there are two spam filters ready in settings on Antispam tab (passive antispam and Google reCaptcha).

![snimek obrazovky 2018-08-17 v 15 20 58](https://user-images.githubusercontent.com/1104383/44268345-813a9f00-a231-11e8-9622-6f651fea03aa.png)

**Comment by gergo85** [comment]
Thank you! I will turn on it.
