### ISSUE TITLE
after error form_description is lost

### ISSUE THREAD

**Issue by plyusninva** [jan-vince/smallcontactform#58]
I override form's property in Twig component tag:
`{% component 'myForm' form_description = 'My other description' %}`
But after an error when filling out the form, form_description is lost

**Comment by plyusninva** [comment]
> ![image](https://user-images.githubusercontent.com/25381948/44384509-de866700-a535-11e8-8495-7ce2d43c9acc.png)

after validate form_description is lost
> ![image](https://user-images.githubusercontent.com/25381948/44384589-1c838b00-a536-11e8-9e03-44b1d3ad93f9.png)

**Comment by plyusninva** [comment]
this can help
https://github.com/jan-vince/smallcontactform/blob/c56e7acd4e32b3382767d0e75a410723695b0541/components/SmallContactForm.php#L295

it also makes it impossible to use my"partials"

**Comment by jan-vince** [comment]
Hi @plyusninva, I cannot replicate this.

Are you using your own partials to render form?

If so, the better approach is to [override components partials](
https://octobercms.com/docs/cms/components#overriding-partials) in your theme folder.

When you use your own partials or expand component's code in your layout/page, onRender method of plugin is not called.

----

You can also set your form description in component definition like:

```
[contactForm]
form_description = "My other description"
```
