### ISSUE TITLE
Validation rules "Required" not work for field type "Checkbox"

### ISSUE THREAD

**Issue by plyusninva** [jan-vince/smallcontactform#59]
1. Validation rules "Required" not work for field type "Checkbox" (data is sent without checking for the need to fill them)
2. "Validation error message" not showed 
3. Tag not marked class "has-error"

![image](https://user-images.githubusercontent.com/25381948/44385364-9d438680-a538-11e8-9eff-20cddd735ccc.png)

**Comment by jan-vince** [comment]
Hi @plyusninva, this is fixed in 1.6.3 version.

Thanks for an issue!
