### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by gergo85** [jan-vince/smallcontactform#6]
I wanted to update the plugin (v1.2.4) and I got the following error message:

"SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'remote_ip' used in key specification without a key length (SQL: alter table `janvince_smallcontactform_messages` add index `janvince_smallcontactform_messages_remote_ip_index`(`remote_ip`))" on line 666 of /var/www/tttweb/data/www/examplewebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by jan-vince** [comment]
I have changed a column type in new (pending) version 1.2.7 - can you please check it?

I don't use MySQL, so I haven't noticed this :(

Thanks for reporting it !

**Comment by gergo85** [comment]
"SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remote_ip' (SQL: alter table `janvince_smallcontactform_messages` add `remote_ip` varchar(255) null)" on line 666 of /var/www/tttweb/data/www/examplewebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php

**Comment by gergo85** [comment]
It works, after I deleted the remote_ip column.

**Comment by jan-vince** [comment]
What is the number of your plugin version right now in OctoberCMS admin?

**Comment by jan-vince** [comment]
Ok, I just wanted to suggest that :)

Thanks for your time!

**Comment by gergo85** [comment]
Now 1.2.7

**Comment by gergo85** [comment]
OK, thank you for fix this issue.
