### ISSUE TITLE
A small and quick question, can I change the layout of the inputs?

### ISSUE THREAD

**Issue by kukrik** [jan-vince/smallcontactform#60]
Now I apologize in advance that my English is not good. I use your plugin for the first time and it is very good.

I know (maybe I got it wrong?) that the default inputs are below each other. As here's an example:

```
.........
.........
<div class="form-group"><input id="contactForm-name" name="name" class="form-control" placeholder="Nimi *" type="text" required=""></div>

<div class="form-group"><input id="contactForm-email" name="email" class="form-control" placeholder="E-post *" type="email"></div>

<div class="form-group"><input id="contactForm-phone" name="phone" class="form-control" placeholder="Telefon" type="text"></div>

<div class="form-group"><textarea id="contactForm-message" name="message" class="form-control" placeholder="Sinu sõnum *" rows="5" required=""></textarea></div>
.........
.........
```
I need to place the inputs to in the group "`<div class ="col-md-6">`" the desired place like here:

```
.........
.........
<div class="col-md-6">

<div class="form-group"><input id="contactForm-name" name="name" class="form-control" placeholder="Nimi *" type="text" required=""></div>

<div class="form-group"><input id="contactForm-email" name="email" class="form-control" placeholder="E-post *" type="email"></div>

<div class="form-group"><input id="contactForm-phone" name="phone" class="form-control" placeholder="Telefon" type="text"></div>

</div>

<div class="col-md-6">

<div class="form-group"><textarea id="contactForm-message" name="message" class="form-control" placeholder="Sinu sõnum *" rows="5" required=""></textarea></div>

</div>
.........
.........
```
My simple question only inputs placement opportunities. I have a bit of experience and knowledge. But how have you solved this issue quickly? What are your best practices?

I am very grateful for any thoughts and suggestions!

Best regards

kukrik

**Comment by jan-vince** [comment]
Hi @kukrik,

you can change class of each wrapper, so you can add your `col-md-6` to every of form's fields.

Better approach would be to add custom classes and create own styling with CSS (I would add all fields in left part `float:left` and a textarea `float:right` styles).

But you cannot fully customize rendering of the form in a way you have written above.

This is where you can add your classes:

![snimek obrazovky 2018-09-16 v 12 19 12](https://user-images.githubusercontent.com/1104383/45595393-32586480-b9ab-11e8-9aae-d1946500187c.png)
