### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by rockstarsun** [jan-vince/smallcontactform#61]
Hi, how do I send a message to the mail?

**Comment by jan-vince** [comment]
Hi @rockstarsun , not sure I understand :(

What do you need to do with the Contact Form?

**Comment by rockstarsun** [comment]
> Привет @rockstarsun , не уверен, что понимаю :(
> 
> Что вам нужно сделать с контактной формой?

Messages that come to be duplicated in the mail

**Comment by rockstarsun** [comment]
@jan-vince Messages that come to be duplicated in the mail

**Comment by rockstarsun** [comment]
Jan Vince.
How to make the form fields duplicated  the moderator in the mail?

Thank you

**Comment by jan-vince** [comment]
Hi @rockstarsun, sorry but I don't understand the problem.

You receive a duplicated notification email?
