### ISSUE TITLE
multiple forms

### ISSUE THREAD

**Issue by AlexAlexWeb** [jan-vince/smallcontactform#66]
Hi! How make multiple forms in your plugin?

**Comment by jan-vince** [comment]
Hi @Alex-studio, there are some hints in documentation. 

But Small Contact Form was meant to be very simple form for Contact page.

Try [Form Builder](https://octobercms.com/plugin/renatio-formbuilder) if you need more complex forms.

**Comment by AlexAlexWeb** [comment]
I think it will be your very useful comment on git hub if you say what hints need to do, and one + in your documentation

**Comment by jan-vince** [comment]
It's quite easy:

1. Create form with some fields (eg. name, email, confirmation)
2. Add components to layout or pages like this:

```
[contactForm fullForm]
```

```
[contactForm emailOnly]
disable_fields = 'name|confirmation'
notification_address_to = 'newsfeed@domain.com'
notification_template = 'notification-newsfeed'
```

The first form will by show with all fields and will send notification to default email. Default email template will be used.

Second form will show only email field. Notification will be sent to newsfeed@domain.com with 'notification-newsfeed' template.


Hope this helps :)

PS: Look at [Hacking form component](
https://github.com/jan-vince/smallcontactform#hacking-a-form-component) part of documentation.
