### ISSUE TITLE
reCaptcha not added

### ISSUE THREAD

**Issue by smartscripts-nl** [jan-vince/smallcontactform#67]
When I try to add reCaptcha, it is not being added to the form. Additionally the scripts which should remove the passive antispam field are not being added.

This seems to indicate something is fundamentally wrong with the plugin: it doesn't read all of its settings. In \JanVince\SmallContactForm\Components\SmallContactForm::onRun() the statement $this->formDescription = $this->property('form_description'); evaluates to null, even though I've entered a form description for the form component in the page.

**Comment by jan-vince** [comment]
Hi @smartscripts-nl, can description problem be related to #58 ?

When I enable reCaptcha in settings, add correct keys, enable option to include necessary JS code, reCaptcha box is shown bellow a form.

Can something be 'fundamentally wrong' on your side? Like missing some plugin settings?

But of course my plugin is far from to be a perfect one and I am open to any PRs to make it better!

**Comment by smartscripts-nl** [comment]
I don't think so: I am only using the Pages plugin and no custom partials etc. I now see that div.g-recaptcha _is_ injected into the page, but doesn't show a captha, probably because the javascript for that is not being injected?

Strangely enough the form_description value now isn't empty anymore. But still the same problems...

**Comment by smartscripts-nl** [comment]
Didn't want to close this issue, my mistake...

**Comment by jan-vince** [comment]
@smartscripts-nl  Have you checked the option `Automatically add necessary JS scripts` option?

![snimek obrazovky 2018-12-13 v 14 43 31](https://user-images.githubusercontent.com/1104383/49942476-adb3ae80-fee5-11e8-9e89-0aa7485a4a5f.png)

**Comment by smartscripts-nl** [comment]
Yes, I have. It does not make any difference. How should these scripts be added? Via a separate script element on the page, or in the combined October javascripts?

**Comment by smartscripts-nl** [comment]
I've found the script element which should load Googles recaptcha scripts. Will analyze further...

**Comment by smartscripts-nl** [comment]
All is well: I got bitten in the foot by a script in one of my plugins, which didn't allow script elements to be injected into the HTML of the page (for security).

Please excuse me for taking your time!

**Comment by jan-vince** [comment]
Hi @smartscripts-nl no problem at all! 

Best regards,

Jan
