### ISSUE TITLE
How to export contact form from CMS

### ISSUE THREAD

**Issue by supriyakhankar** [jan-vince/smallcontactform#68]
I want to export contact form listing from CMS. Any idea how to do that?

**Comment by jan-vince** [comment]
Hi @supriyakhankar, there is an Export button in toolbar:

![snimek obrazovky 2019-01-07 v 8 27 04](https://user-images.githubusercontent.com/1104383/50754476-2cd2a300-1256-11e9-921d-825565a0a942.png)

**Comment by supriyakhankar** [comment]
Thanks.
