### ISSUE TITLE
Labels and placeholders

### ISSUE THREAD

**Issue by Klukies** [jan-vince/smallcontactform#69]
Hey, I was wondering if you could add the possibility to have labels AND placeholders?

**Comment by jan-vince** [comment]
Hi @Klukies, showing both is not a problem.

But what about a content - you probably need also an options to add label text and placeholder text (right now there is only a label text field in form's settings).

Am I right?

**Comment by Klukies** [comment]
Hey, having the ability to show both is just for styling really. It allows for a more creative way to use the contact form. For my ends the content would be the same ;).

**Comment by jan-vince** [comment]
Hi @Klukies,

from version 1.23.0 when `Use placeholders` option is enabled, labels are still present and hidden only by `style` attribute.

So anyone can easily show them by CSS (eg. with `display: block !important`).

Hope this helps :)
