### ISSUE TITLE
Error on settings page

### ISSUE THREAD

**Issue by gergo85** [jan-vince/smallcontactform#7]
In Settings > Small plugins > Contact form page I got the following error message:

Invalid argument supplied for foreach()
/var/www/tttweb/data/www/examplewebsite.com/plugins/janvince/smallcontactform/models/Settings.php line 164

Plugin: 1.3.0
October: 419
PHP: 5.6.30

**Comment by jan-vince** [comment]
I can't reproduce it but the problem is probably in a getTranslated() method, that lacks a fallback value.

I have added it in 1.3.1, so can you please check if this is a cause ?

Thank you.

**Comment by gergo85** [comment]
It works fine. Thanks.

**Comment by jan-vince** [comment]
Me too!
