### ISSUE TITLE
Custom HTML

### ISSUE THREAD

**Issue by hesham-abboud** [jan-vince/smallcontactform#70]
Hello, thanks for your great work.
Is there any way to customize my HTML. For example, I need to put name and email side by side, I can add css class to name input and its wrapper, but what if I need to put it and email in separate wrapper other than the other fields?

**Comment by jan-vince** [comment]
Hi @hesham-abboud , there is no way to manually change generated HTML code. This was meant to be very simple plugin. But look at Form builder in October Marketplace!

**Comment by ghost** [comment]
Hi Jan - I think this would be very easy for you to add... Just create a new field type. Whatever HTML the user puts into a text box, display that exactly. Don't wrap it anything or put anything inside it. Just display the user's input. With this field, you could add an opening div class="col1" for example, or later on a closing "/div" or you could put text above a series of checkboxes. This has lots of uses!``
