### ISSUE TITLE
Hook into successful submission

### ISSUE THREAD

**Issue by plindsay** [jan-vince/smallcontactform#72]
Hi there, thanks for the great plugin - it's very useful :) 

Is it possible to run some code upon a successful submission? For example, when someone submits the form and their details are added I'd also like to subscribe them to a Mailchimp list. Are there any events or 'hooks' that I can use for this purpose?

Kind regards,

Phil

**Comment by jan-vince** [comment]
Hi @plindsay, not now.

But I will add this to my todo list!
