### ISSUE TITLE
Undefined index: name

### ISSUE THREAD

**Issue by StuFromDrum** [jan-vince/smallcontactform#73]
Hi, this is a great plugin. I've used it on another site. But... for some reason I'm now getting an 'Undefined index: name' error on a new installation.

Plugin installs fine, go to Settings, add new fields & save. As soon as I refresh it throws the error and I can no longer access the Settings. Need to uninstall & reinstall, only for the same thing to happen each time.

Plugin v.1.24.0
OctoberCMS build 447

Error:
```
Undefined index: name
/home/vagrant/code/villacrowd/plugins/janvince/smallcontactform/models/Settings.php line 174
```

Any ideas?

**Comment by StuFromDrum** [comment]
Weirdly it works if I copy the array from value field in the system_settings table of my other site (running v.1.20.0) into this new installation and change the field values directly in the db.

As soon as I change any settings within OctoberCMS, and saves, it breaks.

**Comment by jan-vince** [comment]
Hi @StuFromDrum,

I can't replicate this - on clean install everything is just fine.

Try to use SQLite (or other DB than you use now) to see if there is any change.
