### ISSUE TITLE
can this plugin used in partials?

### ISSUE THREAD

**Issue by aurora5161** [jan-vince/smallcontactform#75]
dear jan , thank you for your plugin. it is great! I have a question that can this plugin used in partials? it works well in pages htm, but it seems doesn't work well in partials htm. can you help me ?

**Comment by erwanregnier** [comment]
Hi @aurora5161 , the october Ajax doesn't work with partials, as explained here:
[https://octobercms.com/docs/cms/partials#life-cycle-limitations](https://octobercms.com/docs/cms/partials#life-cycle-limitations)
You need to use it in a layout or page.

**Comment by jan-vince** [comment]
Hi @aurora5161, just as @cryonos wrote - you have to define component in layout or CMS page.

But the component call itself (`{% component 'contactForm' %}`) can be putted into the partial.
