### ISSUE TITLE
Implement Invisible Google reCaptcha

### ISSUE THREAD

**Issue by KoekEnPeer** [jan-vince/smallcontactform#79]
Hi,
At the moment, only the classic Google reCAPTCHA (checkbox 'I'm not a robot') is supported. It would be nice if also invisible reCAPTCHA (or even reCAPTCHA v3) would be supported.

**Comment by jan-vince** [comment]
Hi @KoekEnPeer,

I have added reCaptcha invisible in a new version of the plugin.

*Currently on GitHub. October Marketplace hase some problems building new versions so it will take some time to be available for update from October.*
