### ISSUE TITLE
A need for hidden type?

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallcontactform#80]
Hello,

I'm thinking out loud if there is any need for a hidden type?

For example if you wanted to pass a value from page parameters... like page URL or some other parameter defined in the code or some other plugin... 

Would there be any sense to implement a hidden type? Or it would be better to include this type in the partial manually?

Regard,
Darjan

**Comment by jan-vince** [comment]
I have no use case for hidden fields but why not :)

How would you pass that variable to Contact Form? It would need some customizations of component definition.

PS: I was thinking about adding a custom field type where you can define a field by your own.
