### ISSUE TITLE
Form redirects without validation

### ISSUE THREAD

**Issue by zlobec** [jan-vince/smallcontactform#81]
So,

can somebody try and replicate:
- Fields have validation
- Disable browser validation is checked
- Enable AJAX
- Redirect after submit is checked and Page URL to redirect is set
- do not fill any fields in the form and submit

I have the version 1.25.0 and the form does return validation errors but than at the end of submit it redirects to Page URL set  in the redirect field. It should not redirect, right?

Regard,
Darjan

**Comment by jan-vince** [comment]
I can :)

I fixed this in 1.30.2 - can you please test it?

*PS: I don't like a flash of a form before redirect (when AJAX is used) but have no better solution right now.*
