### ISSUE TITLE
duplicate entry

### ISSUE THREAD

**Issue by mattiak14** [jan-vince/smallcontactform#82]
Hi,
great plugin, everything works fine but I have a problem:
every time a contact request is registered, a duplicate is generated ... both on the db and on the email notification
what could be the reason?

thanks

**Comment by jan-vince** [comment]
You have probably included October scripts and also checked to include them in Contact Form settings.

**Comment by mattiak14** [comment]
what option are you referring to?

**Comment by jan-vince** [comment]
Hi @mattiak14 

In Small Contact Form settings there is a checkbox `Add assets`.

If this is checked and you also included `{% framework extras %}` (as [referred here](http://localhost/october.dev/sprava/system/settings/update/janvince/smallcontactform/settings)), than you can end up with double notification.

<img width="501" alt="scf-assets" src="https://user-images.githubusercontent.com/1104383/75710118-39208780-5cc4-11ea-93ac-4edb787b003b.png">
