### ISSUE TITLE
upload form configuration

### ISSUE THREAD

**Issue by alexandra-toder** [jan-vince/smallcontactform#84]
Hi,
How can I upload the configuration?
I worked on localhost I added some fields and after I put the changes on the dev the form doesn't have the fields anymore. Now on dev, the form looks like that
![image](https://user-images.githubusercontent.com/56544568/66749839-8b871600-ee93-11e9-81f7-751a27cfdae8.png)
thanks!

**Comment by jan-vince** [comment]
Hi @alexandra-toder, configuration is saved in a database so you have to transfer whole database or a part of it.

You can find a configuration in `system_settings` table (in row with `janvince_smallcontactform_settings`).
