### ISSUE TITLE
Contact form not showing after deployment

### ISSUE THREAD

**Issue by TatendaKwaramba** [jan-vince/smallcontactform#86]
Please help I cannot see my contact form after deploying my app but its working fine on localhost

Here is the screenshot of what I am getting

![Screenshot from 2019-11-30 04-33-07](https://user-images.githubusercontent.com/33118227/69894610-a968e700-132a-11ea-99cb-c77beb643c69.png)

Thanks in Advance

**Comment by jan-vince** [comment]
Hi @TatendaKwaramba, this issue is duplicat of #84 - check that out.
