### ISSUE TITLE
Need an image verification code feature to prevent spam.

### ISSUE THREAD

**Issue by alanhwi** [jan-vince/smallcontactform#87]
Hello, This is a Very useful plugin, thank you very much for your works.

One of the problems I'm facing now is spam, because Google is not available in some regions around the world, and Google reCaptcha is invalid in these regions, so if I provide Website message module for these regions, I must use image verification codes to prevent spam mail, Is it possible to add options like "Captcha for Laravel" as an anti-spam option. URL: https://github.com/mewebstudio/captcha

I searched all the Contact form Plugins in Octobercms, But I didn't find any contact form plugin with image verification code. If the plugin adds image verification function, this will be the first Contact form Plugin to integrate the image verification function. This plugin will be more perfect, and it will benefit more people. I hope to consider adding this function, thank you!

**Comment by jan-vince** [comment]
Hi @alanhwi, if you have some spare time to implement this, I will accept such PR.

There is passive spam protection built in Small Contact form and also IP protection, so you can try to use them to prevent spam.
