### ISSUE TITLE
Problem with notification delivery.

### ISSUE THREAD

**Issue by pierzo** [jan-vince/smallcontactform#89]
Information from events log:
SMALL CONTACT FORM ERROR: Notification email address (xxx@wy-szkoleni.pl; xxxx@o2.pl; xxxx@protonmail.com) is invalid! No notification will be delivered!

I use SMTP method on 465 port with SSL
I can properly send my mail template via octoberCMS. 

System version 464
Contact form version  1.40.0

**Comment by jan-vince** [comment]
Hi @pierzo, you should use commas instead of semicolon to separate several email addresses.
It is mentioned in [docs](https://github.com/jan-vince/smallcontactform/blob/master/README.md#allow-notifications).

**Comment by pierzo** [comment]
Works great!
