### ISSUE TITLE
form not submitted, no thrown errors

### ISSUE THREAD

**Issue by karlienfabre** [jan-vince/smallcontactform#90]
Hi, 

Probably more 'a questions' than an issue :)

I'm trying to get the contact form working, but I'm stuck. 
I loaded the component in a page-layout, enabled ajax and imported the framework extras and scripts. 

https://www.technicobikes.be/stockfietsen/test

But if I try to submit the form, nothing happens... even no errors in the console or..
What did I do wrong :-/ 

Thanks for helping me out! 

Brn
Karlien

**Comment by jan-vince** [comment]
Hi @karlienfabre ,

have you tried to use form without AJAX? Are there any errors shown?

Also maybe try to let Small Contact form to load necessary JS and CSS files itself to be sure you have included them right.

Let me know,

Jan
