### ISSUE TITLE
Validation error message not showing

### ISSUE THREAD

**Issue by HermesZum** [jan-vince/smallcontactform#91]
Hello,

The 'Validation error message' does not appear when errors arise, I have already tried Automatically add necessary CSS and JS assets and disabled my JS and CSS, it still does not appear. Any solution?

Regards

**Comment by jan-vince** [comment]
Hi @HermesZum, can you be more specific about this?

In fresh Small Contact Form installation when a field is invalid, I get:

* General validation error in alert box above form
* Specific field validation error beside a field (added tag `<small class=" invalid-feedback">Please enter valid data</small>`)

Can you check, that `<small>` tag is visible?

**Comment by RaHanja** [comment]
Bonjour, moi aussi j'ai une erreur de validation de formulaire, j'ai pas cette tag <small > dans la mienne

Hello, I also have a form validation error, I don't have this <small> tag in mine

**Comment by onshiryuu** [comment]
Hi, I also have this issue, 

When a field is invalid I only receive the default notification.

Neither of these appears:
General validation error in alert box above form
Specific field validation error beside a field (added tag `<small class=" invalid-feedback">Please enter valid data</small>`)

and no, the `<small>` tag was not generated.

**Comment by jan-vince** [comment]
Hi @onshiryuu ,

try to send more details.

What fields are you using and is this problem with any type? (text, textarea, ...)

What CSS framework you use (if any)?

Have you followed [my setup howto?](https://github.com/jan-vince/smallcontactform#setup-new-contact-form)
