### ISSUE TITLE
change default validation error message 

### ISSUE THREAD

**Issue by aaradho** [jan-vince/smallcontactform#92]
Hello,
The 'Validation error message' that I defined in setting of plugin does not appear , In fact, these settings do not work correctly!Is it possible to change default error message in the jQuery validation?
If not how can we change validation error message in small contact form plugin?
Thanks

**Comment by jan-vince** [comment]
Hi @aaradho, I cannot replicate this.

I have fresh installation of Small Contact Form.

I have added:

* General validation messages on Form tab (in plugin's settings)
* Validation messages to fields

When I send invalida data, I have general error above form and field errors by the fields.

Screen is attached:

<img width="810" alt="Snímek obrazovky 2020-05-23 v 19 42 30" src="https://user-images.githubusercontent.com/1104383/82736940-965d2f80-9d2d-11ea-9e40-b845595b35f7.png">
