### ISSUE TITLE
incorrect validation message

### ISSUE THREAD

**Issue by aaradho** [jan-vince/smallcontactform#93]
hello,
I have Equal validation for my fields in form(Required) ,and in view all of them are completed,but validation error message for some of them show valide and correct but for some of them show invalide.
in Inspect of form show that for example class of invalide field is --->class="form-control error is-invalid"
And I have to say that when I disable validation in setting, it gives the same error again. And it is definitely being validated from somewhere else.And that I didn't use a specific css class for that field
Please help me to solve it.
thanks.

**Comment by jan-vince** [comment]
Hi @aaradho, I cannot replicate this.

I have added 3 dropdown fields with some data and `required` validation works.

I can send form when I select all of them, I get error when (e.g.) one of them has empty option selected.

Screen attached (settings and result):

<img width="950" alt="Snímek obrazovky 2020-05-23 v 19 53 03" src="https://user-images.githubusercontent.com/1104383/82737145-07511700-9d2f-11ea-8f69-4ab8643b8286.png">

<img width="817" alt="Snímek obrazovky 2020-05-23 v 19 51 03" src="https://user-images.githubusercontent.com/1104383/82737119-c8bb5c80-9d2e-11ea-89e3-cf3954b497b7.png">
