### ISSUE TITLE
550 5.7.1 Relaying denied

### ISSUE THREAD

**Issue by paaax** [jan-vince/smallcontactform#95]
I'm receiving the following error after the latest update:

_"Expected response code 250 but got code "550", with message "550 5.7.1 Relaying denied
"" on line 457 of /var/www/web1269/html/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php_

I did not change my configuration and it was working just fine before. Any idea what might be the issue?

**Comment by jan-vince** [comment]
Hi @paaax, I have no idea - never seen this before.

Can you test the same configuration with another SMTP server?
