### ISSUE TITLE
plugin is broken

### ISSUE THREAD

**Issue by alexunjm** [jan-vince/smallcontactform#96]
hi,

the plugin is very usefull. I configure it and it works ok, but 2 days later, simply it does not work more.
html view is looking well, but when I submit form, refresh the page and mark inputs as (green) ok, with no messages
when I login as superadmin, the "Contact Form" tab messages do not register the data

I hope, somebody can help me

**Comment by Tayeq** [comment]
Same for me

**Comment by jan-vince** [comment]
Hi @alexunjm and @Tayeq -- any errors in your system log?

Have you updated OctoberCMS core recently?

**Comment by Tayeq** [comment]
@jan-vince I've checked that, issue exists only on homepage (/), because contact form is attached to layout.

October CMS is not calling ::onFormSend, so it's not plugin issue in my opinion

**Comment by alexunjm** [comment]
I apologize for the delay in responding. I will check it @Tayeq. Thanks for your time @jan-vince.
