### ISSUE TITLE
I receive a lot of spam messages even if captcha2 is activated

### ISSUE THREAD

**Issue by faselunare** [jan-vince/smallcontactform#97]
I receive tons of email with messages like this

```

NAME | PchAzBEQJw
-- | --
yazlugo13@gmail.com
Bxratqvz
Contact us!
contactForm

```
``` 

NAME | vFZjdLXaeiONVEsc
-- | --
tiffanyspratt2@gmail.com
LUYWoeuhxsv
Contact us!
contactForm
```

``` 

NAME | sYFDaMXjcvKUIz
-- | --
hubie.goff@yahoo.com
GMHBaAgsU
Contact us!
contactForm

```

**Comment by jan-vince** [comment]
Hi @faselunare i have also some sites with spam even with reCaptcha enabled.

Have you tried an invisible reCaptcha option?

**Comment by faselunare** [comment]
yes, reCaptcha is on with reCaptcha V2 invisible selected
I noticed that the spam wave arrives when post on Facebook, when I make a post and share it in other groups, spam starts to arrive. Then after a few days he goes out and I receive an email every now and then.

**Comment by jan-vince** [comment]
Hi, is this happen with reCaptcha checkbox?


Best reagards,

Jan

**Comment by jan-vince** [comment]
Hi,

I think I have found a bug in my Small Contact Form code for v2invisible backend verification.

I will test it and if so I will publish a new version asap.


Best regards,

Jan
