### ISSUE TITLE
No basic usage example for using the component, without extension, in the docs?

### ISSUE THREAD

**Issue by HellaWiggly** [jan-vince/smallcontactform#99]
Hi there,

I'm interested in using the plugin, and I've read all the documentation in the README.

However it neglects to include a basic usage case for using the component, without overriding any of the parameters?

Or is it the case that you necessarily have to extend the component to use it?

I assumed I could configure in the Small Contact Form settings, then do the following:

```
<div class="container">
    {% component 'contactForm' %}
</div>
```

However when I do this I'm not getting any HTML rendered for the component.

I installed via the plugin manager in the backend and then configured the options in the Small Contact Form settings.

Is there something additional I need to do to get October to use the component?

**Comment by HellaWiggly** [comment]
The bit of the puzzle I was missing was that I needed to add
```
[contactForm]
```
to the page I was using the component on, which is just basic component usage. My bad I'm pretty new to OctoberCMS.

Got there eventually.  Might be worth considering adding a basic usage example to the docs.

**Comment by jan-vince** [comment]
Hi @HellaWiggly, no problem :)
